module.exports = {
  arrowParens: 'always',
  bracketSpacing: true,
  htmlWhitespaceSensitivity: 'ignore',
  printWidth: 100,
  quoteProps: 'consistent',
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  plugins: [require('prettier-plugin-tailwindcss')],
  overrides: [
    {
      files: ['*.html'],
      options: {
        attributeGroups: [
          '^\\*ngIf',
          '^\\*ngFor',
          '^#',
          '^\\[(?!ngClass|ngStyle)',
          '^\\(',
          '^class$',
          '^\\[ngClass\\]$',
          '^style$',
          '^\\[ngStyle\\]$',
          '$DEFAULT',
        ],
        attributeSort: 'ASC',
        parser: 'angular',
        vueIndentScriptAndStyle: true,
      },
    },
  ],
}
