import {
  defineField,
  type BlockName,
  type CombinedFieldOptions,
  type DynamicBlockFieldTypes,
  type GenericDatabase,
  type ResolveFieldUIOptions,
} from '#pruvious/server'
import { Field, type ConditionalLogic, type FieldModel, type GenericField } from '@pruvious/orm'
import type { PropType } from 'vue'
import { blockFieldModel, type BlockFieldModelOptions } from '../../modules/pruvious/blocks/blocksFieldModel'

export default {
  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for server-side use in collection definitions.
   * For client-side usage, import the equivalent function from `#pruvious/client`.
   */
  serverFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
  >(
    options: CombinedFieldOptions<
      FieldModel<
        BlockFieldModelOptions,
        'text',
        DynamicBlockFieldTypes['Casted'][BlockName][],
        DynamicBlockFieldTypes['Populated'][BlockName][],
        DynamicBlockFieldTypes['Input'][BlockName][],
        undefined,
        { [$key in BlockName]: Record<string, GenericField> }
      >,
      BlockFieldModelOptions & ResolveFieldUIOptions<undefined>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >,
  ): Field<
    FieldModel<
      BlockFieldModelOptions,
      'text',
      DynamicBlockFieldTypes['Casted'][BlockName][],
      DynamicBlockFieldTypes['Populated'][BlockName][],
      DynamicBlockFieldTypes['Input'][BlockName][],
      undefined,
      { [$key in BlockName]: Record<string, GenericField> }
    >,
    BlockFieldModelOptions & ResolveFieldUIOptions<undefined>,
    false,
    TRequired,
    TImmutable,
    TAutoGenerated,
    TConditionalLogic,
    GenericDatabase
  > {
    const bound = defineField({
      model: blockFieldModel(),
      castedTypeFn: () => `DynamicBlockFieldTypes['Casted'][BlockName][]`,
      populatedTypeFn: () => `DynamicBlockFieldTypes['Populated'][BlockName][]`,
      inputTypeFn: () => `DynamicBlockFieldTypes['Input'][BlockName][]`,
    }).serverFn.bind(this)
    return bound(options as any) as any
  },

  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for client-side use in Vue components.
   * For server-side usage, import the equivalent function from `#pruvious/server`.
   */
  clientFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
  >(
    options: CombinedFieldOptions<
      FieldModel<
        BlockFieldModelOptions,
        'text',
        DynamicBlockFieldTypes['Casted'][BlockName][],
        DynamicBlockFieldTypes['Populated'][BlockName][],
        DynamicBlockFieldTypes['Input'][BlockName][],
        undefined,
        { [$key in BlockName]: Record<string, GenericField> }
      >,
      BlockFieldModelOptions & ResolveFieldUIOptions<undefined>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >,
  ): { type: PropType<DynamicBlockFieldTypes['Populated'][BlockName][]>; required: true } & {
    field: Field<
      FieldModel<
        BlockFieldModelOptions,
        'text',
        DynamicBlockFieldTypes['Casted'][BlockName][],
        DynamicBlockFieldTypes['Populated'][BlockName][],
        DynamicBlockFieldTypes['Input'][BlockName][],
        undefined,
        { [$key in BlockName]: Record<string, GenericField> }
      >,
      BlockFieldModelOptions & ResolveFieldUIOptions<undefined>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >
  } {
    return null as any
  },

  /**
   * Represents the type structure for this field's configuration options.
   *
   * Note: This is a TypeScript type assertion and does not involve any runtime logic or data.
   */
  TOptions: undefined as unknown as CombinedFieldOptions<
    FieldModel<
      BlockFieldModelOptions,
      'text',
      DynamicBlockFieldTypes['Casted'][BlockName][],
      DynamicBlockFieldTypes['Populated'][BlockName][],
      DynamicBlockFieldTypes['Input'][BlockName][],
      undefined,
      { [$key in BlockName]: Record<string, GenericField> }
    >,
    BlockFieldModelOptions & ResolveFieldUIOptions<undefined>,
    false,
    boolean,
    boolean,
    boolean,
    ConditionalLogic | undefined,
    GenericDatabase
  >,
}
