import {
  type CombinedFieldOptions,
  defineField,
  type GenericDatabase,
  type ResolveFieldUIOptions,
  type TranslatableStringCallback,
} from '#pruvious/server'
import {
  type ConditionalLogic,
  type Field,
  type FieldModel,
  textFieldModel,
  type TextFieldModelOptions,
} from '@pruvious/orm'
import type { ExtractValues } from '@pruvious/utils'
import type { PropType } from 'vue'

export interface ButtonGroupChoice {
  /**
   * An optional label to display in the UI for this choice.
   * If not provided, the `value` will be displayed instead.
   *
   * You can provide either a string or a callback function that returns a string.
   *
   * @example
   * ```ts
   * // Using a string
   * label: 'Yes'
   *
   * // Using a callback
   * label: ({ __ }) => __('pruvious-api', 'Yes')
   * ```
   */
  label?: string | TranslatableStringCallback

  /**
   * Unique string identifier for this choice.
   * This value is stored in the database and returned when the field is selected.
   */
  value: string
}

interface CustomOptions<TChoices extends ButtonGroupChoice[]> {
  /**
   * The choices available for the button group.
   * Each choice must have a unique `value`.
   *
   * @example
   * ```ts
   * choices: [
   *   { label: 'Yes', value: 'yes' },
   *   { label: 'No', value: 'no' },
   * ]
   * ```
   */
  choices: TChoices
}

const customOptions: CustomOptions<ButtonGroupChoice[]> = {
  choices: [],
}

export default {
  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for server-side use in collection definitions.
   * For client-side usage, import the equivalent function from `#pruvious/client`.
   */
  serverFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    const TChoices extends ButtonGroupChoice[],
    const TValues extends ExtractValues<TChoices> = ExtractValues<TChoices>,
  >(
    options: Omit<
      CombinedFieldOptions<
        FieldModel<TextFieldModelOptions<TValues, TValues>, 'text', TValues, TValues, TValues, undefined, undefined>,
        TextFieldModelOptions<TValues, TValues> & CustomOptions<TChoices> & ResolveFieldUIOptions<undefined>,
        false,
        TRequired,
        TImmutable,
        TAutoGenerated,
        TConditionalLogic,
        GenericDatabase
      >,
      'allowEmptyString' | 'maxLength' | 'minLength' | 'trim'
    >,
  ): Field<
    FieldModel<TextFieldModelOptions<TValues, TValues>, 'text', TValues, TValues, TValues, undefined, undefined>,
    TextFieldModelOptions<TValues, TValues> & CustomOptions<TChoices> & ResolveFieldUIOptions<undefined>,
    false,
    TRequired,
    TImmutable,
    TAutoGenerated,
    TConditionalLogic,
    GenericDatabase
  > {
    const bound = defineField({
      model: textFieldModel(),
      default: options.choices[0]?.value,
      customOptions,
      omitOptions: ['allowEmptyString', 'maxLength', 'minLength', 'trim'],
      castedTypeFn: ({ field }) =>
        field.options.choices.map((choice) => `'${choice.value.replaceAll("'", "\\'")}'`).join(' | '),
      populatedTypeFn: ({ field }) =>
        field.options.choices.map((choice) => `'${choice.value.replaceAll("'", "\\'")}'`).join(' | '),
      inputTypeFn: ({ field }) =>
        field.options.choices.map((choice) => `'${choice.value.replaceAll("'", "\\'")}'`).join(' | '),
    }).serverFn.bind(this)
    return bound(options as any) as any
  },

  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for client-side use in Vue components.
   * For server-side usage, import the equivalent function from `#pruvious/server`.
   */
  clientFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    const TChoices extends ButtonGroupChoice[],
    const TValues extends ExtractValues<TChoices> = ExtractValues<TChoices>,
  >(
    options: Omit<
      CombinedFieldOptions<
        FieldModel<TextFieldModelOptions<TValues, TValues>, 'text', TValues, TValues, TValues, undefined, undefined>,
        TextFieldModelOptions<TValues, TValues> & CustomOptions<TChoices> & ResolveFieldUIOptions<undefined>,
        false,
        TRequired,
        TImmutable,
        TAutoGenerated,
        TConditionalLogic,
        GenericDatabase
      >,
      'allowEmptyString' | 'maxLength' | 'minLength' | 'trim'
    >,
  ): { type: PropType<TValues>; required: true } & {
    field: Field<
      FieldModel<TextFieldModelOptions<TValues, TValues>, 'text', TValues, TValues, TValues, undefined, undefined>,
      TextFieldModelOptions<TValues, TValues> & CustomOptions<TChoices> & ResolveFieldUIOptions<undefined>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >
  } {
    return null as any
  },

  /**
   * Represents the type structure for this field's configuration options.
   *
   * Note: This is a TypeScript type assertion and does not involve any runtime logic or data.
   */
  TOptions: undefined as unknown as Omit<
    CombinedFieldOptions<
      FieldModel<TextFieldModelOptions<string, string>, 'text', string, string, string, undefined, undefined>,
      TextFieldModelOptions<string, string> & CustomOptions<ButtonGroupChoice[]> & ResolveFieldUIOptions<undefined>,
      false,
      boolean,
      boolean,
      boolean,
      ConditionalLogic | undefined,
      GenericDatabase
    >,
    'allowEmptyString' | 'maxLength' | 'minLength' | 'trim'
  >,
}
