import {
  defineField,
  limitPopulation,
  type BlockName,
  type CollectionAPI,
  type CombinedFieldOptions,
  type DynamicBlockFieldTypes,
  type DynamicCollectionFieldTypes,
  type GenericDatabase,
  type LanguageCode,
  type ResolveFieldUIOptions,
} from '#pruvious/server'
import {
  bigIntFieldModel,
  type BigIntFieldModelOptions,
  type ConditionalLogic,
  type Field,
  type FieldModel,
  type ForeignKey,
  type GenericField,
} from '@pruvious/orm'
import { isArray, isNull, isNumber, type NonEmptyArray, type StringKeys } from '@pruvious/utils'
import type { PropType } from 'vue'

export interface CustomLinkedBlocksFieldOptions<TCollection extends CollectionAPI['any']['read']> {
  /**
   * The collection to fetch the linked blocks from.
   * The collection must expose a `blocksField` at the field name configured by `blocksField` (defaults to `'blocks'`).
   */
  collection: TCollection & string

  /**
   * Name of the `blocksField` on the linked `collection` that holds the blocks to inline.
   *
   * @default 'blocks'
   */
  blocksField?: (keyof DynamicCollectionFieldTypes['Casted'][TCollection] & string) | undefined

  ui?: {
    /**
     * Defines the field or fields from the `collection` to display in the record selector and data table.
     * Accepts a single field name for a one-line display, or a tuple of two field names to add a grayed-out subtitle.
     *
     * @default 'id'
     *
     * @example
     * 'title'
     * ['title', 'description']
     */
    displayFields?:
      | (keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string)
      | [
          (
            | (keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string)
            | ((keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string) | (string & {}))[]
          ),
          (
            | (keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string)
            | ((keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string) | (string & {}))[]
          ),
        ]

    /**
     * Specifies which languages to show when selecting records.
     *
     * @default 'current'
     */
    languages?: 'all' | 'current' | LanguageCode[]

    /**
     * Field names searched when the user types into the record selector.
     *
     * @default 'id'
     */
    searchFields?:
      | StringKeys<DynamicCollectionFieldTypes['Serialized'][TCollection]>
      | NonEmptyArray<StringKeys<DynamicCollectionFieldTypes['Serialized'][TCollection]>>
  }

  /**
   * Controls whether a foreign key constraint is automatically created when this field is used at the top level of a collection.
   * The constraint references the `id` field in the related `collection`.
   *
   * Available options:
   *
   * - `'cascade'` - Create a foreign key constraint with `ON UPDATE RESTRICT` and `ON DELETE CASCADE` actions.
   * - `'restrict'` - Create a foreign key constraint with `ON UPDATE RESTRICT` and `ON DELETE RESTRICT` actions.
   * - `'set null'` - Create a foreign key constraint with `ON UPDATE RESTRICT` and `ON DELETE SET NULL` actions (default).
   * - `false` - Do not create any foreign key constraint (you can define it manually using the `foreignKeys` option at the collection level).
   *
   * @default 'set null'
   */
  foreignKey?: 'cascade' | 'restrict' | 'set null' | false
}

const customOptions: CustomLinkedBlocksFieldOptions<any> = {
  collection: '',
  ui: {
    displayFields: 'id',
    languages: 'current',
    searchFields: 'id',
  },
  foreignKey: 'set null',
}

type LinkedBlocksPopulated = DynamicBlockFieldTypes['Populated'][BlockName][] | null

export default {
  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for server-side use in collection, singleton, and block definitions.
   * For client-side usage, import the equivalent function from `#pruvious/app`.
   */
  serverFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    TCollection extends CollectionAPI['any']['read'],
  >(
    options: Omit<
      CombinedFieldOptions<
        FieldModel<
          BigIntFieldModelOptions<number, LinkedBlocksPopulated>,
          'bigint',
          number,
          LinkedBlocksPopulated,
          number | string,
          undefined,
          undefined
        >,
        BigIntFieldModelOptions<number, LinkedBlocksPopulated> &
          CustomLinkedBlocksFieldOptions<TCollection> &
          ResolveFieldUIOptions<{ placeholder: true }>,
        true,
        TRequired,
        TImmutable,
        TAutoGenerated,
        TConditionalLogic,
        GenericDatabase
      >,
      'min' | 'max'
    >,
  ): Field<
    FieldModel<
      BigIntFieldModelOptions<number, LinkedBlocksPopulated>,
      'bigint',
      number,
      LinkedBlocksPopulated,
      number | string,
      undefined,
      undefined
    >,
    BigIntFieldModelOptions<number, LinkedBlocksPopulated> &
      CustomLinkedBlocksFieldOptions<TCollection> &
      ResolveFieldUIOptions<{ placeholder: true }>,
    true,
    TRequired,
    TImmutable,
    TAutoGenerated,
    TConditionalLogic,
    GenericDatabase
  > {
    const bound = defineField({
      model: bigIntFieldModel<number, LinkedBlocksPopulated>(),
      nullable: true,
      default: null,
      customOptions: { ...customOptions, min: 1 },
      uiOptions: { placeholder: true },
      validators: [
        async (value, { definition, context }) => {
          if (!isNull(value)) {
            const count = await context.database
              .queryBuilder()
              .selectFrom(definition.options.collection)
              .where('id', '=', value)
              .useCache(context.cache)
              .count()

            if (!count.success) {
              throw new Error(
                context.__('pruvious-api', `Failed to verify existence of ID \`$id\` in collection \`$collection\``, {
                  id: value,
                  collection: definition.options.collection,
                }),
              )
            } else if (count.data === 0) {
              throw new Error(context.__('pruvious-api', 'Record does not exist'))
            }
          }
        },
      ],
      populator: async (value, contextField) => {
        if (!isNumber(value)) {
          return null
        }

        const { definition, context } = contextField
        const blocksFieldName = (definition.options.blocksField ?? 'blocks') as string

        limitPopulation(value, contextField)

        const query = await context.database
          .queryBuilder()
          .selectFrom(definition.options.collection)
          .select([blocksFieldName])
          .where('id', '=', value)
          .useCache(context.cache)
          .populate()
          .first()

        if (!query.success || !query.data) {
          return null
        }

        const blocks = (query.data as Record<string, any>)[blocksFieldName]
        return isArray(blocks) ? blocks : null
      },
      omitOptions: ['min', 'max'],
      populatedTypeFn: () => `DynamicBlockFieldTypes['Populated'][BlockName][] | null`,
    }).serverFn.bind(this)
    return bound({
      ...(options as any),
      _foreignKey:
        options.foreignKey !== false
          ? ({
              referencedCollection: options.collection,
              referencedField: 'id',
              action:
                options.foreignKey === 'cascade'
                  ? ['ON UPDATE RESTRICT', 'ON DELETE CASCADE']
                  : options.foreignKey === 'restrict'
                    ? ['ON UPDATE RESTRICT', 'ON DELETE RESTRICT']
                    : ['ON UPDATE RESTRICT', 'ON DELETE SET NULL'],
            } satisfies Omit<ForeignKey<Record<string, GenericField>>, 'field'>)
          : undefined,
    }) as any
  },

  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for client-side use in Vue components.
   * For server-side usage, import the equivalent function from `#pruvious/server`.
   */
  clientFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    TCollection extends CollectionAPI['any']['read'],
  >(
    options: Omit<
      CombinedFieldOptions<
        FieldModel<
          BigIntFieldModelOptions<number, LinkedBlocksPopulated>,
          'bigint',
          number,
          LinkedBlocksPopulated,
          number | string,
          undefined,
          undefined
        >,
        BigIntFieldModelOptions<number, LinkedBlocksPopulated> &
          CustomLinkedBlocksFieldOptions<TCollection> &
          ResolveFieldUIOptions<{ placeholder: true }>,
        true,
        TRequired,
        TImmutable,
        TAutoGenerated,
        TConditionalLogic,
        GenericDatabase
      >,
      'min' | 'max'
    >,
  ): { type: PropType<LinkedBlocksPopulated>; required: true } & {
    field: Field<
      FieldModel<
        BigIntFieldModelOptions<number, LinkedBlocksPopulated>,
        'bigint',
        number,
        LinkedBlocksPopulated,
        number | string,
        undefined,
        undefined
      >,
      BigIntFieldModelOptions<number, LinkedBlocksPopulated> &
        CustomLinkedBlocksFieldOptions<TCollection> &
        ResolveFieldUIOptions<{ placeholder: true }>,
      true,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >
  } {
    return null as any
  },

  /**
   * Represents the type structure for this field's configuration options.
   *
   * Note: This is a TypeScript type assertion and does not involve any runtime logic or data.
   */
  TOptions: undefined as unknown as Omit<
    CombinedFieldOptions<
      FieldModel<
        BigIntFieldModelOptions<number, LinkedBlocksPopulated>,
        'bigint',
        number,
        LinkedBlocksPopulated,
        number | string,
        undefined,
        undefined
      >,
      BigIntFieldModelOptions<number, LinkedBlocksPopulated> &
        CustomLinkedBlocksFieldOptions<CollectionAPI['any']['read']> &
        ResolveFieldUIOptions<{ placeholder: true }>,
      true,
      boolean,
      boolean,
      boolean,
      ConditionalLogic | undefined,
      GenericDatabase
    >,
    'min' | 'max'
  >,
}
