import {
  type CombinedFieldOptions,
  defineField,
  type GenericDatabase,
  type ResolveFieldUIOptions,
} from '#pruvious/server'
import {
  type ConditionalLogic,
  type Field,
  type FieldModel,
  textFieldModel,
  type TextFieldModelOptions,
} from '@pruvious/orm'
import { isNotNull, isNull } from '@pruvious/utils'
import type { PropType } from 'vue'
import {
  type ColorChoice,
  type ColorChoiceGroup,
  type ExtractColorCastedValues,
  type ExtractColorPopulatedValues,
  flattenColorChoices,
  serializePopulatedType,
} from './color'

interface CustomOptions<TColors extends (string | ColorChoice | ColorChoiceGroup)[]> {
  /**
   * The colors available for this field. Each entry can be:
   *
   * - A CSS color string (e.g. `'#ff0000'`, `'rgb(255 0 0 / 0.5)'`, `'tomato'`).
   * - A `ColorChoice` object with an optional `label`, the casted `value`, and an optional `populate` override.
   * - A `ColorChoiceGroup` object with a translatable `group` label and a list of colors.
   *
   * Every `value` must be a valid CSS color and must be unique across all groups and top-level colors.
   *
   * @example
   * ```ts
   * colors: [
   *   '#ff0000',
   *   { label: 'Brand green', value: '#00ff00' },
   *   {
   *     group: ({ __ }) => __('pruvious-dashboard', 'Brand'),
   *     colors: [
   *       { value: '#0000ff', populate: { name: 'blue', rgb: [0, 0, 255] } },
   *     ],
   *   },
   * ]
   * ```
   */
  colors: TColors
}

const customOptions: CustomOptions<(string | ColorChoice | ColorChoiceGroup)[]> = {
  colors: [],
}

export default {
  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for server-side use in collection definitions.
   * For client-side usage, import the equivalent function from `#pruvious/app`.
   */
  serverFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    const TColors extends (string | ColorChoice | ColorChoiceGroup)[],
    const TCasted extends ExtractColorCastedValues<TColors> = ExtractColorCastedValues<TColors>,
    const TPopulated = ExtractColorPopulatedValues<TColors>,
  >(
    options: Omit<
      CombinedFieldOptions<
        FieldModel<
          TextFieldModelOptions<TCasted, TPopulated>,
          'text',
          NoInfer<TCasted>,
          TPopulated,
          TCasted,
          undefined,
          undefined
        >,
        TextFieldModelOptions<TCasted, TPopulated> & CustomOptions<TColors> & ResolveFieldUIOptions<undefined>,
        true,
        TRequired,
        TImmutable,
        TAutoGenerated,
        TConditionalLogic,
        GenericDatabase
      >,
      'allowEmptyString' | 'maxLength' | 'minLength' | 'trim'
    >,
  ): Field<
    FieldModel<TextFieldModelOptions<TCasted, TPopulated>, 'text', TCasted, TPopulated, TCasted, undefined, undefined>,
    TextFieldModelOptions<TCasted, TPopulated> & CustomOptions<TColors> & ResolveFieldUIOptions<undefined>,
    true,
    TRequired,
    TImmutable,
    TAutoGenerated,
    TConditionalLogic,
    GenericDatabase
  > {
    const bound = defineField({
      model: textFieldModel(),
      nullable: true,
      default: null,
      validators: [
        (value, { context }) => {
          if (isNotNull(value) && !flattenColorChoices(options.colors).some((choice) => choice.value === value)) {
            throw new Error(context.__('pruvious-orm', 'Invalid value'))
          }
        },
      ],
      populator: (value, { definition }) => {
        if (isNull(value)) {
          return null as any
        }
        const colors = (definition.options as any).colors as (string | ColorChoice | ColorChoiceGroup)[]
        const choice = flattenColorChoices(colors).find((c) => c.value === value)
        return (choice && 'populate' in choice ? choice.populate : value) as any
      },
      customOptions: { ...customOptions, trim: false },
      omitOptions: ['allowEmptyString', 'maxLength', 'minLength', 'trim'],
      castedTypeFn: ({ field }) => {
        const parts = flattenColorChoices(field.options.colors).map((choice) => JSON.stringify(choice.value))
        return (parts.length ? parts.join(' | ') : 'string') + ' | null'
      },
      populatedTypeFn: ({ field }) => {
        const choices = flattenColorChoices(field.options.colors)
        const parts = choices.map((choice) =>
          'populate' in choice ? serializePopulatedType(choice.populate) : JSON.stringify(choice.value),
        )
        return (parts.length ? parts.join(' | ') : 'string') + ' | null'
      },
      inputTypeFn: ({ field }) => {
        const parts = flattenColorChoices(field.options.colors).map((choice) => JSON.stringify(choice.value))
        return (parts.length ? parts.join(' | ') : 'string') + ' | null'
      },
    }).serverFn.bind(this)
    return bound(options as any) as any
  },

  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for client-side use in Vue components.
   * For server-side usage, import the equivalent function from `#pruvious/server`.
   */
  clientFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    const TColors extends (string | ColorChoice | ColorChoiceGroup)[],
    const TCasted extends ExtractColorCastedValues<TColors> = ExtractColorCastedValues<TColors>,
    const TPopulated = ExtractColorPopulatedValues<TColors>,
  >(
    options: Omit<
      CombinedFieldOptions<
        FieldModel<
          TextFieldModelOptions<TCasted, TPopulated>,
          'text',
          NoInfer<TCasted>,
          TPopulated,
          TCasted,
          undefined,
          undefined
        >,
        TextFieldModelOptions<TCasted, TPopulated> & CustomOptions<TColors> & ResolveFieldUIOptions<undefined>,
        true,
        TRequired,
        TImmutable,
        TAutoGenerated,
        TConditionalLogic,
        GenericDatabase
      >,
      'allowEmptyString' | 'maxLength' | 'minLength' | 'trim'
    >,
  ): { type: PropType<TPopulated | null>; required: true } & {
    field: Field<
      FieldModel<
        TextFieldModelOptions<TCasted, TPopulated>,
        'text',
        TCasted,
        TPopulated,
        TCasted,
        undefined,
        undefined
      >,
      TextFieldModelOptions<TCasted, TPopulated> & CustomOptions<TColors> & ResolveFieldUIOptions<undefined>,
      true,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >
  } {
    return null as any
  },

  /**
   * Represents the type structure for this field's configuration options.
   *
   * Note: This is a TypeScript type assertion and does not involve any runtime logic or data.
   */
  TOptions: undefined as unknown as Omit<
    CombinedFieldOptions<
      FieldModel<TextFieldModelOptions<string, unknown>, 'text', string, unknown, string, undefined, undefined>,
      TextFieldModelOptions<string, unknown> &
        CustomOptions<(string | ColorChoice | ColorChoiceGroup)[]> &
        ResolveFieldUIOptions<undefined>,
      true,
      boolean,
      boolean,
      boolean,
      ConditionalLogic | undefined,
      GenericDatabase
    >,
    'allowEmptyString' | 'maxLength' | 'minLength' | 'trim'
  >,
}
