import {
  defineField,
  resolveCustomComponentPath,
  walkFieldLayoutItems,
  type CombinedFieldOptions,
  type FieldsLayout,
  type GenericDatabase,
  type ResolveFieldUIOptions,
} from '#pruvious/server'
import {
  Field,
  structuredObjectFieldModel,
  type ConditionalLogic,
  type ExtractCastedTypes,
  type ExtractPopulatedTypes,
  type FieldModel,
  type GenericField,
  type StructuredObjectFieldModelOptions,
  type SubfieldsInput,
} from '@pruvious/orm'
import { isArray, isObject, setProperty } from '@pruvious/utils'
import { hash } from 'ohash'
import type { PropType } from 'vue'
import type { ResolveFromLayersResult } from '../../modules/pruvious/utils/resolve'

interface CustomOptions<TSubfields extends Record<string, GenericField>> {
  /**
   * A key-value object of `Field` instances describing each property of this field.
   *
   * - Object keys represent the subfield names.
   * - Object values are instances of the `Field` class.
   *
   * @example
   * ```ts
   * {
   *   width: numberField({}),
   *   unit: textField({}),
   * }
   *
   * // Example value:
   * {
   *   width: 100,
   *   unit: 'px',
   * }
   * ```
   */
  subfields: TSubfields

  ui?: {
    /**
     * Customizes the subfields layout.
     * If not specified, the subfields are stacked vertically in the order they are defined.
     *
     * @default undefined
     *
     * @example
     * ```ts
     * [
     *   // Single field
     *   'email',
     *
     *   // Half-width field (max-width: 50%)
     *   'firstName | 50%',
     *
     *   // Auto-width field { width: 'auto', flexShrink: 0 }
     *   'middleName | auto',
     *
     *   // Field with custom component styles
     *   {
     *     field: {
     *       name: 'lastName',
     *       style: { maxWidth: '50%' },
     *     },
     *   },
     *
     *   // Field group (row)
     *   {
     *     row: [
     *       // Has maximum width of 8rem
     *       'countryCode | 8rem',
     *
     *       // Takes up the remaining space
     *       'phone',
     *     ],
     *   },
     *
     *   // Horizontal rule
     *   '---',
     *
     *   // Field group (tabs)
     *   {
     *     tabs: [
     *       {
     *         label: ({ __ }) => __('pruvious-dashboard', 'Address'),
     *         fields: ['street | 40%', 'city | 40%', 'zipCode'],
     *       },
     *       {
     *         label: ({ __ }) => __('pruvious-dashboard', 'Contact'),
     *         fields: [
     *           {
     *             // Custom Vue component
     *             // - The component must be resolved using `resolvePruviousComponent()`
     *             //   or `resolveNamedPruviousComponent()`.
     *             // - The import path must be a literal string, not a variable.
     *             // - The import path can be an absolute or relative to the definition file.
     *             component: resolvePruviousComponent('>/components/Dashboard/ContactForm.vue'),
     *           },
     *         ],
     *       },
     *     ],
     *   },
     *
     *   // Card group
     *   {
     *     card: ['comments', 'assignedTo'],
     *   },
     * ]
     * ```
     */
    subfieldsLayout?: FieldsLayout<keyof TSubfields & string> | undefined
  }
}

type ExtractClientSubfields<T extends Record<string, { field: GenericField }>> = {
  [K in keyof T]: T[K]['field']
}

const customOptions: CustomOptions<Record<string, GenericField>> = {
  subfields: {},
  ui: {
    subfieldsLayout: undefined,
  },
}

export default {
  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for server-side use in collection definitions.
   * For client-side usage, import the equivalent function from `#pruvious/client`.
   */
  serverFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    TSubfields extends Record<string, GenericField>,
    TCastedType = ExtractCastedTypes<TSubfields>,
    TPopulatedType = ExtractPopulatedTypes<TSubfields>,
  >(
    options: CombinedFieldOptions<
      FieldModel<
        StructuredObjectFieldModelOptions<TCastedType, TPopulatedType>,
        'text',
        TCastedType,
        TPopulatedType,
        SubfieldsInput<TSubfields>,
        TSubfields,
        undefined
      >,
      StructuredObjectFieldModelOptions<TCastedType, TPopulatedType> &
        CustomOptions<TSubfields> &
        ResolveFieldUIOptions<undefined>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >,
  ): Field<
    FieldModel<
      StructuredObjectFieldModelOptions<TCastedType, TPopulatedType>,
      'text',
      TCastedType,
      TPopulatedType,
      SubfieldsInput<TSubfields>,
      TSubfields,
      undefined
    >,
    StructuredObjectFieldModelOptions<TCastedType, TPopulatedType> &
      CustomOptions<TSubfields> &
      ResolveFieldUIOptions<undefined>,
    false,
    TRequired,
    TImmutable,
    TAutoGenerated,
    TConditionalLogic,
    GenericDatabase
  > {
    const { location }: { fieldType: string; location: ResolveFromLayersResult } = this as any

    if (isArray(customOptions.ui?.subfieldsLayout)) {
      for (const { item, path } of walkFieldLayoutItems(customOptions.ui.subfieldsLayout)) {
        if (isObject(item) && 'component' in item) {
          setProperty(
            customOptions.ui.subfieldsLayout,
            `${path}.component`,
            item.component.includes('/')
              ? hash(
                  resolveCustomComponentPath({
                    component: item.component,
                    file: location.file.absolute,
                    srcDir: location.layer.config.srcDir,
                  }),
                )
              : item.component,
          )
        }
      }
    }

    const bound = defineField({
      model: structuredObjectFieldModel(options.subfields),
      customOptions,
      castedTypeFn: () =>
        `{ ${Object.entries(options.subfields)
          .map(([subfieldName, subfield]) => `${subfieldName}: ${(subfield as any).castedTypeFn(subfield)}`)
          .join(', ')} }`,
      populatedTypeFn: () =>
        `{ ${Object.entries(options.subfields)
          .map(([subfieldName, subfield]) => `${subfieldName}: ${(subfield as any).populatedTypeFn(subfield)}`)
          .join(', ')} }`,
    }).serverFn.bind(this)
    return bound(options as any) as any
  },

  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for client-side use in Vue components.
   * For server-side usage, import the equivalent function from `#pruvious/server`.
   */
  clientFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    TClientSubfields extends Record<string, { field: GenericField }>,
    TSubfields extends Record<string, GenericField> = ExtractClientSubfields<TClientSubfields>,
    TCastedType = ExtractCastedTypes<TSubfields>,
    TPopulatedType = ExtractPopulatedTypes<TSubfields>,
  >(
    options: CombinedFieldOptions<
      FieldModel<
        StructuredObjectFieldModelOptions<TCastedType, TPopulatedType>,
        'text',
        TCastedType,
        TPopulatedType,
        SubfieldsInput<TSubfields>,
        TSubfields,
        undefined
      >,
      StructuredObjectFieldModelOptions<TCastedType, TPopulatedType> &
        // @ts-expect-error
        CustomOptions<TClientSubfields> &
        ResolveFieldUIOptions<undefined>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >,
  ): { type: PropType<TPopulatedType>; required: true } & {
    field: Field<
      FieldModel<
        StructuredObjectFieldModelOptions<TCastedType, TPopulatedType>,
        'text',
        TCastedType,
        TPopulatedType,
        SubfieldsInput<TSubfields>,
        TSubfields,
        undefined
      >,
      StructuredObjectFieldModelOptions<TCastedType, TPopulatedType> &
        // @ts-expect-error
        CustomOptions<TClientSubfields> &
        ResolveFieldUIOptions<undefined>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >
  } {
    return null as any
  },

  /**
   * Represents the type structure for this field's configuration options.
   *
   * Note: This is a TypeScript type assertion and does not involve any runtime logic or data.
   */
  TOptions: undefined as unknown as CombinedFieldOptions<
    FieldModel<
      StructuredObjectFieldModelOptions<Record<string, any>, Record<string, any>>,
      'text',
      Record<string, any>,
      Record<string, any>,
      SubfieldsInput<Record<string, GenericField>>,
      Record<string, GenericField>,
      undefined
    >,
    StructuredObjectFieldModelOptions<Record<string, any>, Record<string, any>> &
      CustomOptions<Record<string, GenericField>> &
      ResolveFieldUIOptions<undefined>,
    boolean,
    boolean,
    boolean,
    boolean,
    ConditionalLogic | undefined,
    GenericDatabase
  >,
}
