import {
  defineField,
  limitPopulation,
  type CollectionAPI,
  type CombinedFieldOptions,
  type DynamicCollectionFieldTypes,
  type GenericDatabase,
  type LanguageCode,
  type ResolveFieldUIOptions,
} from '#pruvious/server'
import {
  junctionFieldModel,
  matrixFieldModel,
  type ConditionalLogic,
  type Field,
  type FieldModel,
  type MatrixFieldModelOptions,
  type Populator,
  type Validator,
} from '@pruvious/orm'
import {
  isArray,
  isEmpty,
  isPositiveInteger,
  promiseAllInBatches,
  uniqueArray,
  type DefaultFalse,
  type NonEmptyArray,
  type StringKeys,
} from '@pruvious/utils'
import type { PropType } from 'vue'

export interface CustomRecordsFieldOptions<
  TCollection extends CollectionAPI['any']['read'],
  TFields extends keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection],
  TPopulate extends boolean | undefined,
> {
  /**
   * The collection name to fetch records from.
   */
  collection: TCollection & string

  /**
   * Fields to return from the selected `collection` when populating this field.
   *
   * By default, only the 'id' field is returned.
   *
   * @default
   * ['id']
   */
  fields?: NonEmptyArray<TFields & string>

  /**
   * An optional field/column name in the referenced `collection` that has the corresponding relation to this collection.
   * That field must also be defined using the `recordsField()`.
   *
   * This only applies if this field is used as a top-level field in a collection.
   * If not provided, the relation is assumed to be unidirectional.
   *
   * @default undefined
   */
  inverseField?: keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string

  /**
   * Specifies which languages to show when selecting collection records.
   *
   * @default 'current'
   */
  languages?: 'all' | 'current' | LanguageCode[]

  /**
   * Controls whether to populate the selected `fields` from the related `collection`.
   *
   * Use this option with care to avoid infinite population loops that can occur when related fields require additional population chains.
   *
   * @default false
   */
  populate?: TPopulate

  ui?: {
    /**
     * Defines the field or fields from the `collection` to display in the data table and select options.
     * Accepts a single field name for a standard display, or a tuple of two field names to create a primary line and a secondary, grayed-out subtitle.
     * The first field in the tuple is always considered the primary field for simplified one-line displays.
     *
     * For advanced customization and string concatenation, you can provide subarrays within tuples:
     *
     * - Field names (strings) get replaced with their corresponding field values (e.g. [['firstName', ' ', 'lastName']]).
     * - The final label combines all subarray items through concatenation (e.g. John Doe).
     *
     * @default 'id'
     *
     * @example
     * 'title'
     * ['title', 'description']
     * [['firstName', ' ', 'lastName'], 'email']
     */
    displayFields?:
      | (keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string)
      | [
          (
            | (keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string)
            | ((keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string) | (string & {}))[]
          ),
          (
            | (keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string)
            | ((keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection] & string) | (string & {}))[]
          ),
        ]

    /**
     * An array of field names to be searched when the user types into the select.
     * The select options will be filtered to include only the items that have a match in at least one of the specified fields.
     *
     * @default 'id'
     *
     * @example
     * 'title'
     * ['title', 'description']
     */
    searchFields?:
      | StringKeys<DynamicCollectionFieldTypes['Serialized'][TCollection]>
      | NonEmptyArray<StringKeys<DynamicCollectionFieldTypes['Serialized'][TCollection]>>

    /**
     * Defines the visual style variant of the component.
     *
     * @default 'accent'
     */
    variant?: 'primary' | 'secondary' | 'accent'
  }
}

const customOptions: CustomRecordsFieldOptions<any, string, boolean> = {
  collection: '',
  fields: ['id'],
  languages: 'current',
  populate: false,
  ui: {
    displayFields: 'id',
    searchFields: 'id',
    variant: 'accent',
  },
}

export default {
  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for server-side use in collection definitions.
   * For client-side usage, import the equivalent function from `#pruvious/app`.
   */
  serverFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    TCollection extends CollectionAPI['any']['read'],
    TFields extends keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection],
    TPopulate extends boolean | undefined,
    TPopulatedType = Pick<
      DynamicCollectionFieldTypes[DefaultFalse<TPopulate> extends true ? 'Populated' : 'Casted'][TCollection],
      TFields
    >[],
  >(
    options: CombinedFieldOptions<
      FieldModel<
        MatrixFieldModelOptions<number[], TPopulatedType>,
        'matrix',
        number[],
        TPopulatedType,
        (number | string)[],
        undefined,
        undefined
      >,
      Omit<MatrixFieldModelOptions<number[], TPopulatedType>, 'deduplicateItems' | 'enforceUniqueItems'> &
        CustomRecordsFieldOptions<TCollection, TFields, TPopulate> &
        ResolveFieldUIOptions<{ placeholder: true }>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >,
  ): Field<
    FieldModel<
      MatrixFieldModelOptions<number[], TPopulatedType>,
      'matrix',
      number[],
      TPopulatedType,
      (number | string)[],
      undefined,
      undefined
    >,
    Omit<MatrixFieldModelOptions<number[], TPopulatedType>, 'deduplicateItems' | 'enforceUniqueItems'> &
      CustomRecordsFieldOptions<TCollection, TFields, TPopulate> &
      ResolveFieldUIOptions<{ placeholder: true }>,
    false,
    TRequired,
    TImmutable,
    TAutoGenerated,
    TConditionalLogic,
    GenericDatabase
  > {
    const uiOptions = { placeholder: true }

    const validators: Validator<
      FieldModel<
        MatrixFieldModelOptions<number[], TPopulatedType>,
        'matrix',
        number[],
        TPopulatedType,
        (number | string)[],
        undefined,
        undefined
      >,
      Omit<MatrixFieldModelOptions<number[], TPopulatedType>, 'deduplicateItems' | 'enforceUniqueItems'> &
        CustomRecordsFieldOptions<TCollection, TFields, TPopulate> &
        ResolveFieldUIOptions<{ placeholder: true }>,
      false,
      boolean,
      boolean,
      boolean,
      ConditionalLogic | undefined,
      GenericDatabase
    >[] = [
      (value, { context, path }, errors) => {
        let hasErrors = false

        for (const [i, id] of value.entries()) {
          if (!isPositiveInteger(id)) {
            errors[`${path}.${i}`] = context.__('pruvious-api', 'The ID must be a positive integer')
            hasErrors = true
          }
        }

        if (hasErrors) {
          throw new Error(context.__('pruvious-orm', 'This field contains invalid values'))
        }
      },
      async (value, { definition, context, path }, errors) => {
        let hasErrors = false

        if (!isEmpty(value)) {
          const chunks: number[][] = []

          for (let i = 0; i < value.length; i += 80) {
            chunks.push(value.slice(i, i + 80))
          }

          const queries = await promiseAllInBatches(
            chunks.map(
              (chunk) => () =>
                context.database
                  .queryBuilder()
                  .selectFrom(definition.options.collection)
                  .select('id')
                  .where('id', 'in', chunk)
                  .select(definition.options.fields)
                  .useCache(context.cache)
                  .all(),
            ),
            50,
          )

          if (queries.every((query) => query.success)) {
            const ids: number[] = queries.flatMap((query) => query.data.map((record) => (record as any).id))

            for (const [i, id] of value.entries()) {
              if (!ids.includes(id)) {
                errors[`${path}.${i}`] = context.__('pruvious-api', 'Record does not exist')
                hasErrors = true
              }
            }
          } else {
            const runtimeError = queries.find((query) => query.runtimeError)?.runtimeError

            if (runtimeError) {
              errors[path] = runtimeError
              hasErrors = true
            } else {
              errors[path] = context.__('pruvious-orm', 'An unknown error occurred')
              hasErrors = true
            }
          }
        }

        if (hasErrors) {
          throw new Error(
            context.__('pruvious-api', 'This field contains IDs that do not exist in the related collection'),
          )
        }
      },
    ]

    const populator: Populator<number[], TPopulatedType> = async (value, contextField) => {
      if (!isEmpty(value)) {
        const { definition, context } = contextField
        const deepPopulate = definition.options.populate

        if (deepPopulate) {
          limitPopulation(value, contextField)
        }

        const chunks: number[][] = []

        for (let i = 0; i < value.length; i += 80) {
          chunks.push(value.slice(i, i + 80))
        }

        const queries = await promiseAllInBatches(
          chunks.map((chunk) => () => {
            const queryBuilder = context.database
              .queryBuilder()
              .selectFrom(definition.options.collection)
              .where('id', 'in', chunk)
              .select(definition.options.fields)
              .useCache(context.cache)
            return deepPopulate ? queryBuilder.populate().all() : queryBuilder.all()
          }),
          50,
        )

        if (queries.every((query) => query.success)) {
          return queries.flatMap((query) => query.data) as any
        }
      }

      return []
    }

    const castedTypeFn = () => 'number[]'
    const populatedTypeFn = ({ field }: any) =>
      `Pick<DynamicCollectionFieldTypes[${field.options.populate ? "'Populated'" : "'Casted'"}]['${field.options.collection}'], ${(field.options.fields ?? ['id']).map((fieldName: string) => `'${fieldName}'`).join(' | ')}>[]`
    const inputTypeFn = () => '(number | string)[]'

    const bound = defineField({
      model: matrixFieldModel<'number', number, number[], TPopulatedType>(),
      customOptions: {
        ...customOptions,
        deduplicateItems: true,
        enforceUniqueItems: true,
        _collectionFieldTransformFn: undefined,
      },
      omitOptions: ['deduplicateItems', 'enforceUniqueItems'],
      uiOptions,
      validators,
      populator: populator as any,
      castedTypeFn,
      populatedTypeFn,
      inputTypeFn,
    }).serverFn.bind(this)
    return bound({
      ...(options as any),
      _collectionFieldTransformFn: () =>
        defineField({
          model: junctionFieldModel<TCollection, number[], TPopulatedType, (string | number)[]>(
            options.collection,
            options.inverseField,
          ),
          sanitizers: [(value) => (isArray(value) ? uniqueArray(value) : value)],
          customOptions: {
            ...customOptions,
            referenceCollection: options.collection,
            inverseField: options.inverseField,
          },
          omitOptions: ['referencedCollection', 'inverseField'] as any,
          uiOptions,
          validators: validators as any,
          populator: populator as any,
          castedTypeFn,
          populatedTypeFn,
          inputTypeFn,
        }).serverFn.bind(this)(options as any),
    }) as any
  },

  /**
   * Creates a new `Field` instance.
   *
   * This function is intended for client-side use in Vue components.
   * For server-side usage, import the equivalent function from `#pruvious/server`.
   */
  clientFn: function <
    const TRequired extends boolean | undefined,
    const TImmutable extends boolean | undefined,
    const TAutoGenerated extends boolean | undefined,
    TConditionalLogic extends ConditionalLogic | undefined,
    TCollection extends CollectionAPI['any']['read'],
    TFields extends keyof DynamicCollectionFieldTypes['Casted' | 'Populated'][TCollection],
    TPopulate extends boolean | undefined,
    TPopulatedType = Pick<
      DynamicCollectionFieldTypes[DefaultFalse<TPopulate> extends true ? 'Populated' : 'Casted'][TCollection],
      TFields
    >[],
  >(
    options: CombinedFieldOptions<
      FieldModel<
        MatrixFieldModelOptions<number[], TPopulatedType>,
        'matrix',
        number[],
        TPopulatedType,
        (number | string)[],
        undefined,
        undefined
      >,
      Omit<MatrixFieldModelOptions<number[], TPopulatedType>, 'deduplicateItems' | 'enforceUniqueItems'> &
        CustomRecordsFieldOptions<TCollection, TFields, TPopulate> &
        ResolveFieldUIOptions<{ placeholder: true }>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >,
  ): { type: PropType<TPopulatedType>; required: true } & {
    field: Field<
      FieldModel<
        MatrixFieldModelOptions<number[], TPopulatedType>,
        'matrix',
        number[],
        TPopulatedType,
        (number | string)[],
        undefined,
        undefined
      >,
      Omit<MatrixFieldModelOptions<number[], TPopulatedType>, 'deduplicateItems' | 'enforceUniqueItems'> &
        CustomRecordsFieldOptions<TCollection, TFields, TPopulate> &
        ResolveFieldUIOptions<{ placeholder: true }>,
      false,
      TRequired,
      TImmutable,
      TAutoGenerated,
      TConditionalLogic,
      GenericDatabase
    >
  } {
    return null as any
  },

  /**
   * Represents the type structure for this field's configuration options.
   *
   * Note: This is a TypeScript type assertion and does not involve any runtime logic or data.
   */
  TOptions: undefined as unknown as CombinedFieldOptions<
    FieldModel<
      MatrixFieldModelOptions<number[], Record<string, any>[]>,
      'matrix',
      number[],
      Record<string, any>[],
      (number | string)[],
      undefined,
      undefined
    >,
    Omit<MatrixFieldModelOptions<number[], Record<string, any>[]>, 'deduplicateItems' | 'enforceUniqueItems'> &
      CustomRecordsFieldOptions<CollectionAPI['any']['read'], any, boolean | undefined> &
      ResolveFieldUIOptions<{ placeholder: true }>,
    false,
    boolean,
    boolean,
    boolean,
    ConditionalLogic | undefined,
    GenericDatabase
  >,
}
