import { defineTranslatableStrings } from '../translatable-strings.definition'

export default defineTranslatableStrings({
  domain: 'pruvious-dashboard',
  language: 'en',
  strings: {
    '(current)': '(current)',
    '**301** - Moved permanently': '**301** - Moved permanently',
    '**302** - Temporarily moved': '**302** - Temporarily moved',
    '$add after': { pattern: '$add after', input: { add: 'string' } },
    '$add before': { pattern: '$add before', input: { add: 'string' } },
    '$count $errors found': {
      pattern: '$count $errors found',
      input: { count: 'number' },
      replacements: { errors: [{ conditions: [{ count: 1 }], output: 'error' }, 'errors'] },
    },
    '$item created': { pattern: '$item created', input: { item: 'string' } },
    '$item deleted': { pattern: '$item deleted', input: { item: 'string' } },
    '$item duplicated': { pattern: '$item duplicated', input: { item: 'string' } },
    '$item link': { pattern: '$item link', input: { item: 'string' } },
    '$item updated': { pattern: '$item updated', input: { item: 'string' } },
    '$timezone time': { pattern: '$timezone time', input: { timezone: 'string' } },
    'A file with the name !!$name!! already exists in the destination folder': {
      pattern: 'A file with the name !!$name!! already exists in the destination folder',
      input: { name: 'string' },
    },
    'A folder with this name already exists': 'A folder with this name already exists',
    'A string to append to the URL or path (e.g. **#anchor** or **?query**).':
      'A string to append to the URL or path (e.g. **#anchor** or **?query**).',
    'Active': 'Active',
    'Add': 'Add',
    'Add $item': { pattern: 'Add $item', input: { item: 'string' } },
    'Add block': 'Add block',
    'Add block before': 'Add block before',
    'Add block after': 'Add block after',
    'Add filter': 'Add filter',
    'Add inner block': 'Add inner block',
    'Add link': 'Add link',
    'Add new folder': 'Add new folder',
    'All fields have been reset to their default values': 'All fields have been reset to their default values',
    'Alt text': 'Alt text',
    '**Allowed types:** $types': { pattern: '**Allowed types:** $types', input: { types: 'string' } },
    'and': 'and',
    'Append': 'Append',
    'Apply': 'Apply',
    'At least one column must be selected': 'At least one column must be selected',
    'Block': 'Block',
    'Block formats': 'Block formats',
    'Blocks': 'Blocks',
    'Cache cleared successfully': 'Cache cleared successfully',
    'Changes that you made may not be saved.': 'Changes that you made may not be saved.',
    'Choose $item': { pattern: 'Choose $item', input: { item: 'string' } },
    'Cancel': 'Cancel',
    'Clear': 'Clear',
    'Clear cache': 'Clear cache',
    'Clear filters': 'Clear filters',
    'Clear selection': 'Clear selection',
    'Click to dismiss': 'Click to dismiss',
    'Close': 'Close',
    'Confirm to !!delete!!': 'Confirm to !!delete!!',
    'Confirm to **move** the selected $selection to **$directory**': {
      pattern: 'Confirm to **move** the selected $selection to **$directory**',
      input: { selection: 'string', directory: 'string' },
    },
    'Contains (case-insensitive)': 'Contains (case-insensitive)',
    'Content copied': 'Content copied',
    'Continue': 'Continue',
    'Convert block to preset': 'Convert block to preset',
    'Convert to preset': 'Convert to preset',
    'Copied': 'Copied',
    'Copy': 'Copy',
    'Copy link to clipboard': 'Copy link to clipboard',
    'Create': 'Create',
    'Create account': 'Create account',
    'Create new $item': { pattern: 'Create new $item', input: { item: 'string' } },
    'Create translation': 'Create translation',
    'Custom target': 'Custom target',
    'Cut': 'Cut',
    'Dashboard': 'Dashboard',
    'Description': 'Description',
    'Desynchronize values': 'Desynchronize values',
    'Do you want to select all $count $items?': {
      pattern: 'Do you want to select all $count $items?',
      input: { count: 'number', items: 'string' },
    },
    'Does not contain (case-insensitive)': 'Does not contain (case-insensitive)',
    'Draft URL': 'Draft URL',
    'Drop files here to upload': 'Drop files here to upload',
    'Duplicate': 'Duplicate',
    'Edit $item': { pattern: 'Edit $item', input: { item: 'string' } },
    'Edit alt text': 'Edit alt text',
    'Edit link': 'Edit link',
    'Element': 'Element',
    'Folder created': 'Folder created',
    'Folder deleted': 'Folder deleted',
    'Folder renamed': 'Folder renamed',
    'Delete': 'Delete',
    'Delete $count $items': { pattern: 'Delete $count $items', input: { count: 'number', items: 'string' } },
    'Deleted $count $items': {
      pattern: 'Deleted $count $items',
      input: { count: 'number', items: 'string' },
    },
    'Deselect': 'Deselect',
    'Deselect $item': { pattern: 'Deselect $item', input: { item: 'string' } },
    'Detach preset': 'Detach preset',
    "Determines the user's login access to the CMS.": "Determines the user's login access to the CMS.",
    'Disable selection': 'Disable selection',
    'Edit': 'Edit',
    'Edit columns': 'Edit columns',
    'Edit file': 'Edit file',
    'Edit filters': 'Edit filters',
    'Edit translation': 'Edit translation',
    'Email': 'Email',
    'Enable selection': 'Enable selection',
    'Ends with (case-insensitive)': 'Ends with (case-insensitive)',
    'Enter alt text...': 'Enter alt text...',
    'Enter full screen': 'Enter full screen',
    'Equal to': 'Equal to',
    'Equal to (case-insensitive)': 'Equal to (case-insensitive)',
    'Exit full screen': 'Exit full screen',
    'false': 'false',
    'file': 'file',
    'File deleted': 'File deleted',
    'File updated': 'File updated',
    'files': 'files',
    'Files': 'Files',
    'Filter $items': { pattern: 'Filter $items', input: { items: 'string' } },
    'Filtered results': 'Filtered results',
    'First name': 'First name',
    'folder': 'folder',
    'Folder is empty': 'Folder is empty',
    'folders': 'folders',
    'Folders': 'Folders',
    'Go to dashboard': 'Go to dashboard',
    'Go to page $page': { pattern: 'Go to page $page', input: { page: 'number' } },
    'Go to start page': 'Go to start page',
    'Greater than': 'Greater than',
    'Greater than or equal to': 'Greater than or equal to',
    'Hide password': 'Hide password',
    'Hyperlink': 'Hyperlink',
    'Inactive': 'Inactive',
    'installWelcomeMessage': 'Welcome to Pruvious! Enter your details to create your primary administrator account.',
    'Inline formats': 'Inline formats',
    'Invalid link': 'Invalid link',
    'Invalid URL': 'Invalid URL',
    'Invalid URL path': 'Invalid URL path',
    'item': 'item',
    'items': 'items',
    'Keyboard shortcuts for blocks are active': 'Keyboard shortcuts for blocks are active',
    'Language': 'Language',
    'Last name': 'Last name',
    'Leave': 'Leave',
    'Less than': 'Less than',
    'Less than or equal to': 'Less than or equal to',
    'Library': 'Library',
    'Library is empty': 'Library is empty',
    'Load more': 'Load more',
    'Log out': 'Log out',
    'Log out user from all active sessions': 'Log out user from all active sessions',
    'Log out from all other sessions': 'Log out from all other sessions',
    'Media': 'Media',
    'Media library': 'Media library',
    '**Minimum height:** $height': { pattern: '**Minimum height:** $height', input: { height: 'number' } },
    '**Minimum width:** $width': { pattern: '**Minimum width:** $width', input: { width: 'number' } },
    'Mirror content to this translation': 'Mirror content to this translation',
    'More options': 'More options',
    'Move': 'Move',
    'Move $count $items': { pattern: 'Move $count $items', input: { count: 'number', items: 'string' } },
    'Move $count $items to': { pattern: 'Move $count $items to', input: { count: 'number', items: 'string' } },
    'Moved $count $items': {
      pattern: 'Moved $count $items',
      input: { count: 'number', items: 'string' },
    },
    'Move down': 'Move down',
    'Move up': 'Move up',
    'Name': 'Name',
    'New name': 'New name',
    'Next page': 'Next page',
    'No': 'No',
    'No $items found': { pattern: 'No $items found', input: { items: 'string' } },
    'No $items matching the current filter were found': {
      pattern: 'No $items matching the current filter were found',
      input: { items: 'string' },
    },
    'No blocks found': 'No blocks found',
    'No fields to display': 'No fields to display',
    'No icons found': 'No icons found',
    'Not equal to': 'Not equal to',
    'My profile': 'My profile',
    'Open': 'Open',
    'Open $item': { pattern: 'Open $item', input: { item: 'string' } },
    'Open $item in new tab': { pattern: 'Open $item in new tab', input: { item: 'string' } },
    'Open in new tab': 'Open in new tab',
    'Open preview in new tab': 'Open preview in new tab',
    'Open root folder': 'Open root folder',
    'or': 'or',
    'Password': 'Password',
    'Paste': 'Paste',
    'Paste after': 'Paste after',
    'Paste block from clipboard': 'Paste block from clipboard',
    'Relationship (rel)': 'Relationship (rel)',
    'Reload preview': 'Reload preview',
    'Remember me': 'Remember me',
    'Replace': 'Replace',
    'Please ensure all block fields are valid before converting the block to a preset':
      'Please ensure all block fields are valid before converting the block to a preset',
    'Preset detached': 'Preset detached',
    'Preview': 'Preview',
    'Previous page': 'Previous page',
    'Profile updated': 'Profile updated',
    'Public URL': 'Public URL',
    'Publish': 'Publish',
    'Redirects to': 'Redirects to',
    'Redo (($count))': { pattern: 'Redo (($count))', input: { count: 'number' } },
    'Remove': 'Remove',
    'Rename': 'Rename',
    'Rename folder': 'Rename folder',
    'Required': 'Required',
    'Restore defaults': 'Restore defaults',
    'Root folder': 'Root folder',
    'Save': 'Save',
    'Save draft': 'Save draft',
    'Search $items...': { pattern: 'Search $items...', input: { items: 'string' } },
    'Search blocks...': 'Search blocks...',
    'Search icons...': 'Search icons...',
    'Search media...': 'Search media...',
    'Search results for:': 'Search results for:',
    'Select': 'Select',
    'Select $item': { pattern: 'Select $item', input: { item: 'string' } },
    'Select icon': 'Select icon',
    'Select from media library': 'Select from media library',
    'Sign in': 'Sign in',
    'Show all $items': { pattern: 'Show all $items', input: { items: 'string' } },
    'Show password': 'Show password',
    'Showing $from to $to of $total $items': {
      pattern: 'Showing $from to $to of $total $items',
      input: { from: 'number', to: 'number', total: 'number', items: 'string' },
    },
    'Some filters are not displayed and are omitted from the user interface':
      'Some filters are not displayed and are omitted from the user interface',
    'Sort in ascending order': 'Sort in ascending order',
    'Sort in descending order': 'Sort in descending order',
    'Starts with (case-insensitive)': 'Starts with (case-insensitive)',
    'Status': 'Status',
    'Synchronize values': 'Synchronize values',
    'Target': 'Target',
    'Test path or URL': 'Test path or URL',
    'The $item does not exist': { pattern: 'The $item does not exist', input: { item: 'string' } },
    'The **$language** translation of this $item does not exist. Do you want to create it?': {
      pattern: 'The **$language** translation of this $item does not exist. Do you want to create it?',
      input: { language: 'string', item: 'string' },
    },
    'The block **$block** cannot be pasted here': {
      pattern: 'The block **$block** cannot be pasted here',
      input: { block: 'string' },
    },
    'The block has been converted into a preset': 'The block has been converted into a preset',
    'The default **alt** attribute value for the image': 'The default **alt** attribute value for the image',
    'The filter in the query string cannot be displayed in the user interface.':
      'The filter in the query string cannot be displayed in the user interface.',
    'The folder name must be lowercase and URL-friendly': 'The folder name must be lowercase and URL-friendly',
    'The file **$file** exceeds the upload limit of $limit': {
      pattern: 'The file **$file** exceeds the upload limit of $limit',
      input: { file: 'string', limit: 'string' },
    },
    'The file does not meet the requirements': 'The file does not meet the requirements',
    'The filename without the extension': 'The filename without the extension',
    'The image does not meet the requirements': 'The image does not meet the requirements',
    "The page you're looking for doesn't exist.": "The page you're looking for doesn't exist.",
    'The **rel** attribute specifies the relationship between the current document and the linked document.':
      'The **rel** attribute specifies the relationship between the current document and the linked document.',
    'The user has been logged out from all active sessions': 'The user has been logged out from all active sessions',
    'There are no compatible blocks that can be added to the selected slot':
      'There are no compatible blocks that can be added to the selected slot',
    'There are no folders where the selected $selection can be moved to': {
      pattern: 'There are no folders where the selected $selection can be moved to',
      input: { selection: 'string' },
    },
    'This action will overwrite the content in the **$language** translation.': {
      pattern: 'This action will overwrite the content in the **$language** translation.',
      input: { language: 'string' },
    },
    'This field cannot be displayed in the UI': 'This field cannot be displayed in the UI',
    'This field is required': 'This field is required',
    'Translation created': 'Translation created',
    'true': 'true',
    'Undo (($count))': { pattern: 'Undo (($count))', input: { count: 'number' } },
    'Change': 'Change',
    'Change icon': 'Change icon',
    'Coordinated Universal Time (UTC)': 'Coordinated Universal Time (UTC)',
    'Untitled': 'Untitled',
    'Update': 'Update',
    'Update alt text': 'Update alt text',
    'Upload': 'Upload',
    'Upload file(s)': 'Upload file(s)',
    'Upload limit is $limit': { pattern: 'Upload limit is $limit', input: { limit: 'string' } },
    'Uploaded $count $files': {
      pattern: 'Uploaded $count $files',
      input: { count: 'number' },
      replacements: { files: [{ conditions: [{ count: 1 }], output: 'file' }, 'files'] },
    },
    'View': 'View',
    'View $item': { pattern: 'View $item', input: { item: 'string' } },
    'View file': 'View file',
    'View translation': 'View translation',
    'Yes': 'Yes',
    "You don't have permission to access this page.": "You don't have permission to access this page.",
    'You have been logged out from all other sessions': 'You have been logged out from all other sessions',
    'You must first allow the app access to the clipboard': 'You must first allow the app access to the clipboard',
  },
})
