import type { BlockName } from '#pruvious/server'
import { isObject, isString, pick } from '@pruvious/utils'
import { useClipboard, useEventListener, type UseClipboardReturn } from '@vueuse/core'
import { getUser } from '../../../../modules/pruvious/auth/utils.client'

export type PruviousClipboardData =
  | {
      pruviousClipboardDataType: 'blocks'
      data: ({ $key: BlockName } & Record<string, any>)[]
    }
  | {
      pruviousClipboardDataType: 'structure-item'
      data: { $type: string } & Record<string, any>
    }
  | {
      pruviousClipboardDataType: 'record'
      data: { $collection: string } & Record<string, any>
    }
  | {
      pruviousClipboardDataType: 'singleton'
      data: { $singleton: string } & Record<string, any>
    }

let _clipboard: UseClipboardReturn<true>

const usePruviousClipboardSource = () => useState<string>('pruvious-clipboard-source', () => 'null')

/**
 * Composable that provides reactive clipboard data for Pruvious objects.
 */
export const usePruviousClipboardData = () =>
  useState<PruviousClipboardData | null>('pruvious-clipboard-data', () => null)

/**
 * Reactive clipboard API that provides the ability to respond to clipboard commands (cut, copy, and paste).
 */
export function usePruviousClipboard() {
  const { text, copy: _copy, copied } = initClipboard()

  return {
    copy: (data: PruviousClipboardData | null) => {
      usePruviousClipboardData().value = data
      _copy(JSON.stringify(data))
    },
    copied,
    data: computed<PruviousClipboardData | null>(() => {
      if (text.value) {
        try {
          const parsed = JSON.parse(text.value)
          if (isValidClipboardData(parsed)) {
            return parsed
          }
        } catch {}
      }
      return null
    }),
  }
}

function initClipboard() {
  if (!_clipboard) {
    const source = usePruviousClipboardSource()
    const user = getUser()

    _clipboard = useClipboard({ source })

    if (user?.smartClipboard) {
      useEventListener(window, 'focus', inspectClipboard)
      inspectClipboard()
    }
  }

  return _clipboard
}

async function inspectClipboard() {
  try {
    const text = await navigator.clipboard.readText()
    const parsed = JSON.parse(text)
    if (isValidClipboardData(parsed)) {
      usePruviousClipboardData().value = parsed
    }
  } catch {}
}

/**
 * Validates that a parsed JSON value matches one of the supported `PruviousClipboardData` shapes.
 * Used to guard the OS clipboard inspector against malformed or attacker-controlled payloads.
 *
 * @param parsed - The parsed JSON value to validate.
 * @returns `true` when the value is a well-formed Pruvious clipboard payload, otherwise `false`.
 */
function isValidClipboardData(parsed: any): parsed is PruviousClipboardData {
  if (!isObject(parsed) || !isString(parsed.pruviousClipboardDataType)) {
    return false
  }
  switch (parsed.pruviousClipboardDataType) {
    case 'blocks':
      return Array.isArray(parsed.data) && parsed.data.every((item: any) => isObject(item) && isString(item.$key))
    case 'structure-item':
      return isObject(parsed.data) && isString(parsed.data.$type)
    case 'record':
      return isObject(parsed.data) && isString(parsed.data.$collection)
    case 'singleton':
      return isObject(parsed.data) && isString(parsed.data.$singleton)
    default:
      return false
  }
}

/**
 * Shape of the field definition properties consulted when building or applying a clipboard payload.
 */
type ClipboardFieldShape = { autoGenerated?: boolean; immutable?: boolean; ui?: { disabled?: boolean } }

/**
 * Returns whether a field should be excluded from a record/singleton clipboard payload.
 * Auto-generated, immutable, and `ui.disabled` fields are skipped because they are not editable in the update form.
 *
 * @param field - The field definition to inspect.
 * @returns `true` when the field is not editable and should be skipped, otherwise `false`.
 */
export function isClipboardSkippedField(field: ClipboardFieldShape): boolean {
  return !!(field.autoGenerated || field.immutable || field.ui?.disabled)
}

/**
 * Builds the editable subset of a record/singleton form state for clipboard copy.
 * Fields flagged via `isClipboardSkippedField`, fields whose name is in `skipFieldNames` (e.g. ownership fields),
 * and field names absent from the data are excluded from the result.
 *
 * @param data - The current form state to extract values from.
 * @param fields - The collection or singleton field definitions.
 * @param skipFieldNames - Additional field names to exclude (e.g. `authorField`, `editorsField`).
 * @returns A new object containing only the editable, copyable field values.
 */
export function buildClipboardFieldValues(
  data: Record<string, any>,
  fields: Record<string, ClipboardFieldShape>,
  skipFieldNames: string[] = [],
): Record<string, any> {
  const skipSet = new Set(skipFieldNames)
  const includedKeys = Object.keys(fields).filter(
    (name) => !skipSet.has(name) && !isClipboardSkippedField(fields[name]!) && name in data,
  )
  return pick(data, includedKeys)
}

/**
 * Merges incoming clipboard values into the current form state.
 * Only keys present in `fields` and not flagged via `isClipboardSkippedField` are applied.
 * Keys listed in `skipFieldNames` and sentinel keys starting with `$` are silently ignored;
 * any other unrecognized keys are returned in `skipped` for user-facing reporting.
 *
 * @param current - The current form state to merge into.
 * @param incoming - The clipboard payload values to apply.
 * @param fields - The target collection or singleton field definitions.
 * @param skipFieldNames - Field names to silently ignore (e.g. `authorField`, `editorsField`).
 * @returns An object with the merged form state and the list of incoming keys that were reported as skipped.
 */
export function applyClipboardFieldValues(
  current: Record<string, any>,
  incoming: Record<string, any>,
  fields: Record<string, ClipboardFieldShape>,
  skipFieldNames: string[] = [],
): { merged: Record<string, any>; skipped: string[] } {
  const skipSet = new Set(skipFieldNames)
  const merged: Record<string, any> = { ...current }
  const skipped: string[] = []

  for (const key of Object.keys(incoming)) {
    if (key.startsWith('$') || skipSet.has(key)) {
      continue
    }
    const field = fields[key]
    if (field && !isClipboardSkippedField(field)) {
      merged[key] = incoming[key]
    } else {
      skipped.push(key)
    }
  }

  return { merged, skipped }
}
