import {
  type Collections,
  type LanguageCode,
  collections,
  database,
  getCollectionFromEvent,
  getLinkIndex,
  getRecordTranslations,
  getSingletonFromEvent,
  translateRelURL,
} from '#pruvious/server'
import type { GenericField } from '@pruvious/orm'
import { isArray, isNull, isObject, isRelURL, isString } from '@pruvious/utils'

/**
 * Default implementation for a collection `duplicate` function.
 *
 * Behavior:
 *
 * - Returns a shallow copy of `source` suitable for inserting into the same collection.
 * - The `author` field (`recordField({ collection: 'Users' })` named `author`) is set to the current user.
 * - For unique text fields, appends ` (copy)` to the value so the new record does not collide with the source.
 *   Unique fields of other types are stripped so the user can fill them in before saving.
 * - `autoGenerated` fields are removed from the result.
 *   The collection API endpoint also strips `id` and (for translatable collections) `translations` after this function returns.
 *
 * Use it directly when defining a collection:
 *
 * ```ts
 * defineCollection({
 *   // ...
 *   duplicate: duplicateDefault,
 * })
 * ```
 */
export async function duplicateDefault({ source }: { source: Record<string, any> }): Promise<any> {
  const collection = await getCollectionFromEvent()
  const userId = currentUserId()
  const result: Record<string, any> = { ...source }
  const translatable = !!(collection.definition.meta as any)?.translatable
  const sourceLanguage = translatable && isString(source.language) ? source.language : null

  for (const [fieldName, field] of Object.entries(collection.definition.fields)) {
    if (field.autoGenerated) {
      delete result[fieldName]
      continue
    }

    if (isAuthorField(fieldName, field)) {
      result[fieldName] = userId
      continue
    }

    const uniqueConstraint = getUniqueConstraint(field)
    if (uniqueConstraint) {
      const kind = classifyLeaf(field)

      if (kind === 'text' && isString(result[fieldName])) {
        const scopeLanguage = uniqueConstraint.perLanguage ? sourceLanguage : null
        result[fieldName] = await findFreeCopyValue(collection.name, fieldName, result[fieldName], scopeLanguage)
      } else {
        delete result[fieldName]
      }
    }
  }

  return result
}

/**
 * Default implementation for a collection `copyTranslation` function.
 *
 * Behavior:
 *
 * - Returns a copy of `source` shaped for the target-language record.
 * - The `author` field is set to the current user.
 * - Single-record fields (`recordField({})`) that point at a translatable collection are remapped to the sibling
 *   record in `targetLanguage`. If no sibling exists, the value becomes `null`.
 * - Multi-record fields (`recordsField({})`) that point at a translatable collection are remapped element-by-element;
 *   ids without a sibling in the target language are dropped.
 * - Link fields (`linkField({})`) whose `url` uses the `rel://` protocol are translated via {@link translateRelURL}.
 *   When no equivalent exists in the target language the original `url` is kept as a fallback.
 * - Text fields whose value contains `rel://` URLs (e.g. `richTextField`, `editorField`, or any string with embedded
 *   internal links) have each `rel://` occurrence translated to the target language. URLs without a target-language
 *   equivalent are left untouched.
 * - Nested fields (`repeaterField`, `objectField`, `structureField`, `blocksField`) are walked recursively so the same
 *   rules apply to references buried inside them.
 * - `autoGenerated` fields are stripped, and when `operation === 'update'` `immutable` fields are stripped too,
 *   mirroring what the collection copy-translation endpoint does after this function returns.
 *
 * Use it directly when defining a collection:
 *
 * ```ts
 * defineCollection({
 *   // ...
 *   copyTranslation: copyTranslationDefault,
 * })
 * ```
 */
export async function copyTranslationDefault({
  source,
  targetLanguage,
  operation,
}: {
  source: Record<string, any>
  sourceLanguage: LanguageCode
  targetLanguage: LanguageCode
  operation: 'create' | 'update'
}): Promise<any> {
  const collection = await getCollectionFromEvent()
  return remapForTranslation(source, collection.definition.fields, targetLanguage, {
    stripImmutable: operation === 'update',
  })
}

/**
 * Default implementation for a singleton `copyTranslation` function.
 *
 * Behavior matches {@link copyTranslationDefault}, but without the `operation` parameter:
 * the singleton copy-translation endpoint always strips `immutable` fields after this function returns.
 *
 * Use it directly when defining a singleton:
 *
 * ```ts
 * defineSingleton({
 *   // ...
 *   copyTranslation: copyTranslationDefaultSingleton,
 * })
 * ```
 */
export async function copyTranslationDefaultSingleton({
  source,
  targetLanguage,
}: {
  source: Record<string, any>
  sourceLanguage: LanguageCode
  targetLanguage: LanguageCode
}): Promise<any> {
  const singleton = await getSingletonFromEvent()
  return remapForTranslation(source, singleton.definition.fields, targetLanguage, { stripImmutable: true })
}

async function remapForTranslation(
  source: Record<string, any>,
  fields: Record<string, GenericField>,
  targetLanguage: LanguageCode,
  opts: { stripImmutable: boolean },
): Promise<Record<string, any>> {
  const userId = currentUserId()
  const result: Record<string, any> = { ...source }

  for (const [fieldName, field] of Object.entries(fields)) {
    if (field.autoGenerated) {
      delete result[fieldName]
      continue
    }

    if (opts.stripImmutable && field.immutable) {
      delete result[fieldName]
      continue
    }

    if (isAuthorField(fieldName, field)) {
      result[fieldName] = userId
      continue
    }

    result[fieldName] = await translateValue(result[fieldName], field, targetLanguage)
  }

  return result
}

async function translateValue(value: any, field: GenericField, targetLanguage: LanguageCode): Promise<any> {
  const kind = classifyField(field, value)

  switch (kind.kind) {
    case 'record': {
      if (!isFiniteNumber(value)) {
        return value
      }
      return (await translateRecordId(kind.collection, value, targetLanguage)) ?? null
    }

    case 'records': {
      if (!isArray(value)) {
        return value
      }
      const translated: number[] = []
      for (const id of value) {
        if (!isFiniteNumber(id)) {
          continue
        }
        const next = await translateRecordId(kind.collection, id, targetLanguage)
        if (next !== null) {
          translated.push(next)
        }
      }
      return translated
    }

    case 'link': {
      if (!isObject(value) || !isString(value.url) || !isRelURL(value.url)) {
        return value
      }
      const translatedUrl = await translateRelURL(value.url, targetLanguage)
      return { ...value, url: translatedUrl ?? value.url }
    }

    case 'repeater': {
      if (!isArray(value)) {
        return value
      }
      const items: any[] = []
      for (const item of value) {
        if (!isObject(item)) {
          items.push(item)
          continue
        }
        items.push(await translateNested(item, kind.subfields, targetLanguage))
      }
      return items
    }

    case 'object': {
      if (!isObject(value)) {
        return value
      }
      return translateNested(value, kind.subfields, targetLanguage)
    }

    case 'structure': {
      if (!isArray(value)) {
        return value
      }
      const items: any[] = []
      for (const item of value) {
        if (!isObject(item) || !isString(item.$key)) {
          items.push(item)
          continue
        }
        const subfields = kind.structure[item.$key]
        if (!subfields) {
          items.push(item)
          continue
        }
        items.push({ ...(await translateNested(item, subfields, targetLanguage)), $key: item.$key })
      }
      return items
    }

    case 'blocks': {
      if (!isArray(value)) {
        return value
      }
      const { blocks } = (await import('#pruvious/server/blocks')) as {
        blocks: Record<string, { fields: Record<string, GenericField> }>
      }
      const items: any[] = []
      for (const item of value) {
        if (!isObject(item) || !isString(item.$key) || !blocks[item.$key]) {
          items.push(item)
          continue
        }
        const subfields = blocks[item.$key]!.fields
        items.push({ ...(await translateNested(item, subfields, targetLanguage)), $key: item.$key })
      }
      return items
    }

    default:
      if (isString(value) && value.includes('rel://')) {
        return translateEmbeddedRelURLs(value, targetLanguage)
      }
      return value
  }
}

async function translateEmbeddedRelURLs(value: string, targetLanguage: LanguageCode): Promise<string> {
  const relRegex = /rel:\/\/[^\s"'<>]+/g
  const matches: { start: number; end: number; raw: string }[] = []
  let match: RegExpExecArray | null

  while ((match = relRegex.exec(value)) !== null) {
    matches.push({ start: match.index, end: match.index + match[0].length, raw: match[0] })
  }

  if (matches.length === 0) {
    return value
  }

  let result = value
  for (let i = matches.length - 1; i >= 0; i--) {
    const m = matches[i]!
    const decoded = m.raw.replace(/&amp;/g, '&')
    const translated = await translateRelURL(decoded, targetLanguage)
    if (translated === null || translated === decoded) {
      continue
    }
    const reencoded = translated.replace(/&(?!(?:amp|lt|gt|quot|apos|#\d+|#x[0-9a-f]+);)/gi, '&amp;')
    result = result.slice(0, m.start) + reencoded + result.slice(m.end)
  }

  return result
}

async function translateNested(
  item: Record<string, any>,
  subfields: Record<string, GenericField>,
  targetLanguage: LanguageCode,
): Promise<Record<string, any>> {
  const next: Record<string, any> = { ...item }
  for (const [subfieldName, subfield] of Object.entries(subfields)) {
    next[subfieldName] = await translateValue(next[subfieldName], subfield, targetLanguage)
  }
  return next
}

async function translateRecordId(
  collectionName: string,
  recordId: number,
  targetLanguage: LanguageCode,
): Promise<number | null> {
  const target = (collections as Record<string, any>)[collectionName]
  if (!target?.meta?.translatable) {
    return recordId
  }

  if (target.meta.routing?.enabled) {
    const index = await getLinkIndex()
    const source = (index.records[collectionName] ?? []).find((record) => record.id === recordId)
    if (source) {
      if (isNull(source.translations)) {
        return recordId
      }
      const sibling = getRecordTranslations(index, collectionName, source).find(
        (record) => record.language === targetLanguage,
      )
      return sibling ? sibling.id : null
    }
  }

  const sourceQuery = await database()
    .queryBuilder()
    .selectFrom(collectionName as keyof Collections)
    .select(['translations'] as any)
    .where('id', '=', recordId)
    .first()

  if (!sourceQuery.success || !sourceQuery.data) {
    return null
  }

  const translationsKey = (sourceQuery.data as Record<string, any>).translations
  if (!isString(translationsKey)) {
    return recordId
  }

  const siblingQuery = await database()
    .queryBuilder()
    .selectFrom(collectionName as keyof Collections)
    .select(['id'] as any)
    .where('translations' as any, '=', translationsKey)
    .where('language' as any, '=', targetLanguage)
    .first()

  return siblingQuery.success && siblingQuery.data ? ((siblingQuery.data as Record<string, any>).id as number) : null
}

type FieldKind =
  | { kind: 'record'; collection: keyof Collections & string }
  | { kind: 'records'; collection: keyof Collections & string }
  | { kind: 'link' }
  | { kind: 'repeater'; subfields: Record<string, GenericField> }
  | { kind: 'object'; subfields: Record<string, GenericField> }
  | { kind: 'structure'; structure: Record<string, Record<string, GenericField>> }
  | { kind: 'blocks' }
  | { kind: 'other' }

function classifyField(field: GenericField, value: any): FieldKind {
  const model: any = field.model
  const options: any = field.options ?? {}
  const dataType: string | undefined = model?.dataType

  if (dataType === 'bigint' && isString(options.collection)) {
    return { kind: 'record', collection: options.collection }
  }

  if ((dataType === 'junction' || dataType === 'matrix') && isString(options.collection)) {
    return { kind: 'records', collection: options.collection }
  }

  if (dataType === 'text' && options.allowedReferences !== undefined && isObject(model?.subfields)) {
    return { kind: 'link' }
  }

  if (dataType === 'text' && isObject(model?.structure)) {
    return { kind: 'structure', structure: model.structure }
  }

  if (dataType === 'text' && options.allowRootBlocks !== undefined) {
    return { kind: 'blocks' }
  }

  if (dataType === 'text' && isObject(model?.subfields)) {
    return isArray(value)
      ? { kind: 'repeater', subfields: model.subfields }
      : { kind: 'object', subfields: model.subfields }
  }

  return { kind: 'other' }
}

function classifyLeaf(field: GenericField): 'text' | 'other' {
  const model: any = field.model
  const options: any = field.options ?? {}
  if (
    model?.dataType === 'text' &&
    !isObject(model?.subfields) &&
    !isObject(model?.structure) &&
    options.allowRootBlocks === undefined &&
    options.allowedReferences === undefined
  ) {
    return 'text'
  }
  return 'other'
}

function isAuthorField(fieldName: string, field: GenericField): boolean {
  const options: any = field.options ?? {}
  return fieldName === 'author' && options.collection === 'Users'
}

function getUniqueConstraint(field: GenericField): { perLanguage: boolean } | null {
  const options: any = field.options ?? {}
  if (options.unique) {
    return { perLanguage: !!(typeof options.unique === 'object' && options.unique?.perLanguage) }
  }
  for (const validator of (field.validators ?? []) as any[]) {
    if (validator?.__pruviousUnique) {
      return { perLanguage: !!validator.__pruviousUnique.perLanguage }
    }
  }
  return null
}

async function findFreeCopyValue(
  collectionName: keyof Collections,
  fieldName: string,
  sourceValue: string,
  scopeLanguage: string | null,
): Promise<string> {
  const base = stripCopySuffix(sourceValue)
  const useSpaces = sourceValue.length === 0 ? false : sourceValue.includes(' ')

  for (let attempt = 1; attempt <= 1000; attempt++) {
    const candidate = formatCopyCandidate(base, attempt, useSpaces)
    if (!(await valueExists(collectionName, fieldName, candidate, scopeLanguage))) {
      return candidate
    }
  }

  return formatCopyCandidate(base, Date.now(), useSpaces)
}

function stripCopySuffix(value: string): string {
  if (value.length === 0) {
    return ''
  }
  const spaced = value.match(/^(.*) \(copy(?:\s+\d+)?\)$/)
  if (spaced) {
    return spaced[1]
  }
  const slugged = value.match(/^(.*)-copy(?:-\d+)?$/)
  if (slugged) {
    return slugged[1]
  }
  return value
}

function formatCopyCandidate(base: string, attempt: number, useSpaces: boolean): string {
  if (base.length === 0) {
    return attempt === 1 ? 'copy' : `copy-${attempt}`
  }
  if (useSpaces) {
    return attempt === 1 ? `${base} (copy)` : `${base} (copy ${attempt})`
  }
  return attempt === 1 ? `${base}-copy` : `${base}-copy-${attempt}`
}

async function valueExists(
  collectionName: keyof Collections,
  fieldName: string,
  value: string,
  scopeLanguage: string | null,
): Promise<boolean> {
  let qb = database()
    .queryBuilder()
    .selectFrom(collectionName)
    .select(['id'] as any)
    .where(fieldName as any, '=', value)

  if (scopeLanguage) {
    qb = qb.where('language' as any, '=', scopeLanguage)
  }

  const result = await qb.first()
  return result.success && !!result.data
}

function currentUserId(): number | null {
  const auth = useEvent().context.pruvious?.auth
  return auth?.isLoggedIn && auth.user ? (auth.user as { id: number }).id : null
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value)
}
