import { execa, type ResultPromise } from 'execa'
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'pathe'
import { appendDeployLogChunk, writeDeployLog } from '../deployLog'

export interface RunProjectSyncInput {
  deploymentId: number
  projectPath: string
  sqlitePath: string
  buildCommand: { cmd: string; args: string[] }
  envVars: { key: string; value: string }[]
  /**
   * Hard timeout for both the Node-server build step and the spawned sync
   * child. Without it the child could hang indefinitely if the Pruvious
   * server plugin doesn't fire `process.exit(0)` (e.g. NITRO_PRESET wasn't
   * honoured, plugin failed to load, custom user plugin swallowed an error).
   */
  timeoutMs: number
}

export async function runProjectSync(input: RunProjectSyncInput): Promise<void> {
  const { deploymentId, projectPath, sqlitePath, buildCommand, envVars, timeoutMs } = input

  if (!existsSync(projectPath)) {
    throw new Error(`Project path does not exist: ${projectPath}`)
  }

  const syncBuildEnv: NodeJS.ProcessEnv = { ...process.env, NITRO_PRESET: 'node-server' }
  for (const { key, value } of envVars) {
    syncBuildEnv[key] = value
  }

  await writeDeployLog(deploymentId, '[hub] running sync build (NITRO_PRESET=node-server)')
  await runStreamed(deploymentId, buildCommand.cmd, buildCommand.args, {
    cwd: projectPath,
    env: syncBuildEnv,
    timeoutMs,
  })

  const outputServerEntry = join(projectPath, '.output', 'server', 'index.mjs')
  if (!existsSync(outputServerEntry)) {
    throw new Error(`Expected sync build output not found at ${outputServerEntry}`)
  }

  const bootstrapDir = join(projectPath, '.pruvious')
  await mkdir(bootstrapDir, { recursive: true })
  const bootstrapPath = join(bootstrapDir, '_hub-sync.mjs')
  await writeFile(bootstrapPath, bootstrapScript(outputServerEntry), 'utf8')

  await writeDeployLog(deploymentId, `[hub] running sync against ${sqlitePath}`)
  const runEnv: NodeJS.ProcessEnv = { ...process.env, PRUVIOUS_SYNC_DB: sqlitePath, NITRO_PORT: '0' }
  for (const { key, value } of envVars) {
    runEnv[key] = value
  }

  await runStreamed(deploymentId, 'node', [bootstrapPath], { cwd: projectPath, env: runEnv, timeoutMs })
}

function bootstrapScript(serverEntryAbsolutePath: string): string {
  return [
    '// Auto-generated by @pruvious/hub-app. Safe to delete.',
    `import('${serverEntryAbsolutePath.replace(/'/g, "\\'")}').catch((err) => {`,
    `  console.error('[pruvious] sync bootstrap failed:', err && err.stack || err)`,
    `  process.exit(1)`,
    `})`,
    '',
  ].join('\n')
}

interface RunStreamedOptions {
  cwd: string
  env?: NodeJS.ProcessEnv
  timeoutMs?: number
}

async function runStreamed(
  deploymentId: number,
  command: string,
  args: string[],
  options: RunStreamedOptions,
): Promise<void> {
  const child: ResultPromise = execa(command, args, {
    cwd: options.cwd,
    env: options.env,
    stdout: 'pipe',
    stderr: 'pipe',
    reject: false,
    timeout: options.timeoutMs,
  })

  child.stdout?.on('data', (data) => {
    void appendDeployLogChunk(deploymentId, data.toString('utf8'))
  })
  child.stderr?.on('data', (data) => {
    void appendDeployLogChunk(deploymentId, data.toString('utf8'))
  })

  const result = await child

  if (result.timedOut) {
    throw new Error(`Command \`${command} ${args.join(' ')}\` timed out after ${options.timeoutMs}ms`)
  }
  if (result.failed || result.exitCode !== 0) {
    throw new Error(`Command \`${command} ${args.join(' ')}\` exited with code ${result.exitCode}`)
  }
}
