import {
  buttonGroupField,
  chipsField,
  defineTemplate,
  deleteUpload,
  insertInto,
  numberField,
  resolveMediaCategory,
  selectField,
  selectFrom,
  switchField,
  textField,
  translatableTextField,
} from '#pruvious/server'
import { Field, objectFieldModel } from '@pruvious/orm'
import { normalizePath } from '@pruvious/storage'
import { isArray, isDefined, isNull, isObject, isPositiveInteger, isString, toArray } from '@pruvious/utils'
import mime from 'mime'
import { extname } from 'pathe'

function multipartField() {
  const field = new Field({
    model: objectFieldModel<{ key: string; parts: { partNumber: number; etag: string }[] }>(),
    options: {},
    validators: [
      (value, { context }) => {
        if (
          !isNull(value) &&
          (!isString(value.key) ||
            !isArray(value.parts) ||
            value.parts.some((part) => !isObject(part) || !isPositiveInteger(part.partNumber) || !isString(part.etag)))
        ) {
          return context.__('pruvious-orm', 'Invalid value')
        }
      },
    ],
  })

  ;(field as any).castedTypeFn = () => '{ key: string; parts: { partNumber: number, etag: string }[] }'
  ;(field as any).populatedTypeFn = () => '{ key: string; parts: { partNumber: number, etag: string }[] }'
  ;(field as any).inputTypeFn = () => '{ key: string; parts: { partNumber: number, etag: string }[] }'
  ;(field as any).options.ui = { dataTable: false }

  return field
}

export default defineTemplate(() => ({
  fields: {
    path: textField({
      ui: { label: ({ __ }) => __('pruvious-dashboard', 'Path'), placeholder: 'e.g. /folder/file.jpg' },
      required: true,
      unique: { errorMessage: ({ __ }) => __('pruvious-api', 'The path must be unique') },
      validators: [
        (value, { context }) => {
          try {
            const type =
              context.customData._uploadType ??
              (context.getSanitizedInputValue('type') === 'file' ? 'file' : 'directory')
            const normalizedPath = normalizePath(value, type)
            if (normalizedPath === value) {
              return
            }
          } catch {}
          throw new Error(context.__('pruvious-api', 'Invalid path'))
        },
      ],
      inputFilters: {
        beforeInputValidation: async (value, { context }) => {
          if (context.operation === 'insert' && isString(value) && context.getSanitizedInputValue('type') === 'file') {
            const ext = extname(value)
            const overwrite = !!context.customData._overwrite
            let path = value
            let index = 0

            if (!isObject(context.cache['_tmp'])) {
              context.cache['_tmp'] = {}
            }

            if (!isArray(context.cache['_tmp']['_resolvedUploadsPaths'])) {
              context.cache['_tmp']['_resolvedUploadsPaths'] = []
            }

            while (true) {
              const uploadsCountQuery = await selectFrom('Uploads').where('path', '=', path).count()
              const existsInCache = context.cache['_tmp']['_resolvedUploadsPaths'].includes(path)
              if ((!uploadsCountQuery.success || uploadsCountQuery.data === 0) && !existsInCache) {
                break
              }
              if (overwrite) {
                await deleteUpload(path)
                break
              } else {
                path = (ext ? value.slice(0, -ext.length) : value) + `-${++index}` + ext
              }
            }

            context.cache['_tmp']['_resolvedUploadsPaths'].push(path)

            return path
          }

          return value
        },
      },
    }),
    type: buttonGroupField({
      ui: { label: ({ __ }) => __('pruvious-dashboard', 'Type') },
      choices: [
        { value: 'directory', label: ({ __ }) => __('pruvious-api', 'Directory') },
        { value: 'file', label: ({ __ }) => __('pruvious-api', 'File') },
      ],
      required: true,
      immutable: true,
    }),
    level: numberField({
      ui: { dataTable: false },
      autoGenerated: true,
      inputFilters: {
        beforeQueryExecution: (_, { context }) => {
          const path = context.getSanitizedInputValue('path')
          if (isDefined(path)) {
            return path.slice(1).split('/').length - 1
          }
        },
      },
    }),
    category: selectField({
      ui: { label: ({ __ }) => __('pruvious-dashboard', 'Category') },
      choices: [
        { value: 'document', label: ({ __ }) => __('pruvious-dashboard', 'cat:document') },
        { value: 'image', label: ({ __ }) => __('pruvious-dashboard', 'cat:image') },
        { value: 'audio', label: ({ __ }) => __('pruvious-dashboard', 'cat:audio') },
        { value: 'video', label: ({ __ }) => __('pruvious-dashboard', 'cat:video') },
        { value: 'archive', label: ({ __ }) => __('pruvious-dashboard', 'cat:archive') },
        { value: 'code', label: ({ __ }) => __('pruvious-dashboard', 'cat:code') },
        { value: 'font', label: ({ __ }) => __('pruvious-dashboard', 'cat:font') },
        { value: '3d', label: ({ __ }) => __('pruvious-dashboard', 'cat:3d') },
        { value: 'data', label: ({ __ }) => __('pruvious-dashboard', 'cat:data') },
        { value: 'system', label: ({ __ }) => __('pruvious-dashboard', 'cat:system') },
        { value: 'text', label: ({ __ }) => __('pruvious-dashboard', 'cat:text') },
        { value: 'other', label: ({ __ }) => __('pruvious-dashboard', 'cat:other') },
        { value: '', label: ({ __ }) => __('pruvious-dashboard', 'None') },
      ],
      autoGenerated: true,
      immutable: true,
      inputFilters: {
        beforeQueryExecution: {
          order: 11,
          callback: (_, { context }) => {
            if (context.operation === 'insert') {
              const mime = context.getSanitizedInputValue('mime')
              return mime ? resolveMediaCategory(mime) : ''
            }
          },
        },
      },
    }),
    mime: textField({
      ui: { label: ({ __ }) => __('pruvious-dashboard', 'MIME type') },
      autoGenerated: true,
      immutable: true,
      inputFilters: {
        beforeQueryExecution: (_, { context }) => {
          if (context.operation === 'insert') {
            const path = context.getSanitizedInputValue('path')
            const type = context.getSanitizedInputValue('type')
            if (type === 'file') {
              const ext = extname(path)
              return mime.getType(ext) || 'application/octet-stream'
            } else {
              return ''
            }
          }
        },
      },
    }),
    size: numberField({
      ui: { label: ({ __ }) => __('pruvious-dashboard', 'Size'), suffix: 'bytes' },
      min: 0,
    }),
    description: translatableTextField({
      allowLineBreaks: false,
      ui: {
        label: ({ __ }) => __('pruvious-dashboard', 'Description'),
        description: ({ __ }) =>
          __(
            'pruvious-dashboard',
            'Short description of the file used for alt text in images and accessibility purposes.',
          ),
      },
    }),
    etag: textField({
      ui: { label: ({ __ }) => __('pruvious-dashboard', 'ETag') },
    }),
    images: chipsField({
      ui: { dataTable: false },
      enforceUniqueItems: true,
    }),
    imageWidth: numberField({
      ui: { label: ({ __ }) => __('pruvious-dashboard', 'Image width'), suffix: 'px' },
      min: 0,
    }),
    imageHeight: numberField({
      ui: { label: ({ __ }) => __('pruvious-dashboard', 'Image height'), suffix: 'px' },
      min: 0,
    }),
    multipart: multipartField(),
    isLocked: switchField({
      ui: { dataTable: false },
    }),
  },
  api: {
    create: false,
    update: false,
    delete: false,
  },
  author: true,
  editors: true,
  indexes: [{ fields: ['type'] }, { fields: ['level'] }, { fields: ['category'] }],
  translatable: false,
  hooks: {
    beforeQueryExecution: [
      async ({ operation, customData }) => {
        if (operation !== 'select' && !customData._allowUploadsQueries) {
          throw new Error(
            'The `Uploads` collection should not be modified directly. Instead, use these functions to handle uploads: `putUpload`, `moveUpload`, `updateUpload`, `deleteUpload`',
          )
        }
      },
    ],
    afterQueryExecution: [
      async (context) => {
        if (context.operation === 'insert' || context.operation === 'update') {
          for (const item of toArray(context.sanitizedInput).values()) {
            const path = item.path as string

            if (path) {
              const parts = path.slice(1).split('/')

              while (parts.pop() && parts.length) {
                await insertInto('Uploads')
                  .values({ path: `/${parts.join('/')}`, type: 'directory', author: item.author })
                  .withCustomContextData({ _allowUploadsQueries: true })
                  .run()
              }
            }
          }
        }
      },
    ],
  },
  ui: {
    hidden: true,
    indexPage: {
      table: {
        orderBy: [
          { field: 'type', direction: 'asc' },
          { field: 'path', direction: 'asc' },
        ],
      },
    },
  },
}))
