const { parseQueryString, stringifyQueryParameters } = require('@pruvious-test/shared')
const { Database } = require('./app/BaseQuery')
const {
  createPage,
  deletePage,
  getPage,
  getPageTranslations,
  queryPages,
  updatePage,
  getPageDraftUrl,
  sanitizeAllowedPageBlocks,
  validatePageFields,
} = require('./app/PageQuery')
const {
  createPost,
  deletePost,
  getAnyPost,
  getPost,
  getPostTranslations,
  queryPosts,
  updatePost,
  validatePostFields,
} = require('./app/PostQuery')
const {
  createPreset,
  deletePreset,
  getPreset,
  getPresetTranslations,
  queryPresets,
  updatePreset,
  validatePresetFields,
} = require('./app/PresetQuery')
const {
  createRole,
  deleteRole,
  getRole,
  getRoleUsers,
  queryRoles,
  updateRole,
  validateRoleFields,
} = require('./app/RoleQuery')
const {
  clearCache,
  flush,
  getSetting,
  getSettings,
  rebuildSitemap,
  updateSettings,
  validateSettingsFields,
} = require('./app/SettingQuery')
const {
  createUpload,
  deleteUpload,
  getUpload,
  queryUploads,
  updateUpload,
  validateUploadFields,
} = require('./app/UploadQuery')
const {
  createUser,
  deleteUser,
  getCombinedCapabilities,
  getUser,
  getUserRole,
  listCapabilities,
  queryUsers,
  revokeAllAccessToken,
  updateUser,
  verifyCredentials,
  validateUserFields,
} = require('./app/UserQuery')
const { addJob, getQueuedJobs } = require('./app/worker')
const { walkBlockRecords, getBlockRecord, getBlock } = require('./app/utils')

module.exports = {
  addJob,
  clearCache,
  createPage,
  createPost,
  createPreset,
  createRole,
  createUpload,
  createUser,
  Database,
  deletePage,
  deletePost,
  deletePreset,
  deleteRole,
  deleteUpload,
  deleteUser,
  flush,
  getAnyPost,
  getBlock,
  getBlockRecord,
  getCombinedCapabilities,
  getPage,
  getPageDraftUrl,
  getPageTranslations,
  getPost,
  getPostTranslations,
  getPreset,
  getPresetTranslations,
  getQueuedJobs,
  getRole,
  getRoleUsers,
  getSetting,
  getSettings,
  getUpload,
  getUser,
  getUserRole,
  listCapabilities,
  parseQueryString,
  queryPages,
  queryPosts,
  queryPresets,
  queryRoles,
  queryUploads,
  queryUsers,
  rebuildSitemap,
  revokeAllAccessToken,
  sanitizeAllowedPageBlocks,
  stringifyQueryParameters,
  updatePage,
  updatePost,
  updatePreset,
  updateRole,
  updateSettings,
  updateUpload,
  updateUser,
  validatePageFields,
  validatePostFields,
  validatePresetFields,
  validateRoleFields,
  validateSettingsFields,
  validateUploadFields,
  validateUserFields,
  verifyCredentials,
  walkBlockRecords,
}
