import { isInteger, isObject } from '@pruvious/utils'
import { Field, FieldModel, type GenericDatabase, type GenericSanitizedInputFilter } from '../core'
import { numberFieldModel, type NumberFieldModelOptions } from '../field-models'

/**
 * Generates a `createdAt` field that stores the timestamp of when a record was created.
 */
export function createdAtField(): Field<
  FieldModel<NumberFieldModelOptions<number, number>, 'numeric', number, number, string | number, undefined>,
  {},
  false,
  false,
  true,
  true,
  undefined,
  GenericDatabase
> {
  return new Field({
    model: numberFieldModel(),
    nullable: false,
    immutable: true,
    autoGenerated: true,
    options: {},
    inputFilters: {
      beforeQueryExecution: createdAtFieldBeforeQueryExecution,
    },
  }) as any
}

/**
 * Sets the `createdAt` field to the current timestamp before query execution.
 */
export const createdAtFieldBeforeQueryExecution: GenericSanitizedInputFilter = (_, { context }) => {
  if (context.operation === 'insert') {
    if (!isObject(context.cache['__tmp'])) {
      context.cache['__tmp'] = {}
    }

    if (
      !isInteger(context.cache['__tmp']['__timestamp']) ||
      context.cache['__tmp']['__timestamp'] < -8640000000000000 ||
      context.cache['__tmp']['__timestamp'] > 8640000000000000
    ) {
      context.cache['__tmp']['__timestamp'] = Date.now()
    }

    return context.cache['__tmp']['__timestamp']
  }
}
