<template>
  <PruviousDashboardPage>
    <template #header>
      <div class="pui-row">
        <span class="pui-shrink-0">{{ __('pruvious-dashboard', 'My account') }}</span>
        <span v-if="auth.user" :title="auth.user.email" class="pui-muted pui-truncate">({{ auth.user.email }})</span>
      </div>
    </template>

    <PruviousFields
      v-if="data"
      v-model:conditionalLogic="conditionalLogic"
      v-model:modelValue="data"
      :conditionalLogicResolver="conditionalLogicResolver"
      :data="data"
      :errors="errors"
      :fields="structure.data.fields"
      :layout="structure.data.fieldsLayout"
      :syncedFields="[]"
      :translatable="false"
      @commit="history.push($event)"
      @queueConditionalLogicUpdate="queueConditionalLogicUpdate($event)"
      @update:modelValue="(_, path) => queueConditionalLogicUpdate(path)"
      dataContainerName="Users"
      dataContainerType="collection"
      operation="update"
    />

    <PruviousDashboardHistoryScrollState />

    <template #footer>
      <div class="pui-justify-between">
        <PruviousDashboardHistoryButtons
          v-if="data"
          v-model="data"
          :history="history"
          @update:modelValue="
            () => {
              errors = {}
              queueConditionalLogicUpdate('$reset')
            }
          "
        />

        <div class="pui-row pui-ml-auto">
          <PUIButton
            v-pui-tooltip="__('pruvious-dashboard', 'Sign out from all other devices')"
            @click="signOutOtherDevices()"
            variant="outline"
          >
            <Icon mode="svg" name="tabler:plug-connected-x" />
          </PUIButton>

          <PUIButton :variant="history.isDirty.value ? 'primary' : 'outline'" @click="saveData()">
            <span>{{ __('pruvious-dashboard', 'Save') }}</span>
            <Icon mode="svg" name="tabler:device-floppy" />
          </PUIButton>
        </div>
      </div>
    </template>
  </PruviousDashboardPage>
</template>

<script lang="ts" setup>
import {
  __,
  dashboardBasePath,
  dashboardMiddleware,
  deserializeTranslatableStringCallbacks,
  History,
  parseConditionalLogic,
  prepareFieldData,
  pruviousDashboardGet,
  pruviousDashboardPatch,
  pruviousDashboardPost,
  storeAuthToken,
  useAuth,
  useDashboardContentLanguage,
  useLanguage,
} from '#pruvious/client'
import { ConditionalLogicResolver } from '@pruvious/orm/conditional-logic-resolver'
import { puiDialog } from '@pruvious/ui/pui/dialog'
import { usePUIHotkeys } from '@pruvious/ui/pui/hotkeys'
import { puiHTMLInit } from '@pruvious/ui/pui/html'
import { usePUIOverlayCounter } from '@pruvious/ui/pui/overlay'
import { puiQueueToast } from '@pruvious/ui/pui/toast'
import { puiTooltipInit } from '@pruvious/ui/pui/tooltip'
import { blurActiveElement, isDefined, isString, isUndefined, lockAndLoad, toArray } from '@pruvious/utils'
import { useDebounceFn } from '@vueuse/core'

definePageMeta({
  path: dashboardBasePath + 'me',
  middleware: [
    (to) => dashboardMiddleware(to, 'default'),
    (to) => dashboardMiddleware(to, 'auth-guard'),
    (to) =>
      dashboardMiddleware(to, ({ __, hasPermission, puiQueueToast }) => {
        if (!hasPermission('update-account')) {
          puiQueueToast(__('pruvious-dashboard', 'Redirected'), {
            type: 'error',
            description: __('pruvious-dashboard', 'You do not have permission to access the page `$page`', {
              page: to.path,
            }),
            showAfterRouteChange: true,
          })
          return navigateTo(dashboardBasePath + 'overview')
        }
      }),
  ],
})

await puiHTMLInit()
puiTooltipInit()

useHead({
  title: __('pruvious-dashboard', 'My account'),
})

const [structure, user] = await Promise.all([pruviousDashboardGet('me/structure'), pruviousDashboardGet('me')])
const data = ref<Record<string, any>>({})

if (structure.success) {
  setData(user.data)
} else {
  throw new Error('Failed to fetch data from: /me/structure')
}

const auth = useAuth()
const conditionalLogicResolver = new ConditionalLogicResolver()
let conditionalLogicDependencies: Record<string, boolean> = {}
const conditionalLogic = ref(resolveConditionalLogic())
const conditionalLogicUpdateQueue = new Set<(string & {}) | '$resolve' | '$reset'>()
const errors = ref<Record<string, string>>({})
const history = new History({
  omit: Object.entries(structure.data.fields)
    .filter(([_, field]) => field.autoGenerated || field.immutable)
    .map(([fieldName]) => fieldName),
}).push(data.value)
const isSubmitting = ref(false)
const { listen } = usePUIHotkeys()
const overlayCounter = usePUIOverlayCounter()
const dashboardLanguage = useLanguage()
const contentLanguage = useDashboardContentLanguage()

listen('save', () => {
  if (!overlayCounter.value) {
    blurActiveElement()
    setTimeout(saveData)
  }
})

function resolveConditionalLogic(reset = true) {
  conditionalLogicResolver.setInput(data.value)
  conditionalLogicDependencies = {}
  if (reset) {
    conditionalLogicResolver.setConditionalLogic(parseConditionalLogic(structure.data?.fields ?? {}, data.value))
  }
  return conditionalLogicResolver.resolve()
}

function queueConditionalLogicUpdate(path?: (string & {}) | string[] | '$resolve' | '$reset') {
  if (isUndefined(path) || path === '$resolve') {
    conditionalLogicUpdateQueue.add('$resolve')
  } else if (path === '$reset') {
    conditionalLogicUpdateQueue.add('$reset')
  } else {
    toArray(path).forEach((p) => conditionalLogicUpdateQueue.add(p))
  }
  updateConditionalLogicDebounced()
}

const updateConditionalLogicDebounced = useDebounceFn(() => {
  const queue = [...conditionalLogicUpdateQueue]
  conditionalLogicUpdateQueue.clear()
  if (queue.some((path) => path === '$reset')) {
    conditionalLogic.value = resolveConditionalLogic(true)
  } else {
    if (queue.some((path) => isString(path) && !isDefined(conditionalLogicDependencies[path]))) {
      const parsedConditionalLogic = parseConditionalLogic(structure.data.fields, data.value)
      for (const from of Object.keys(parsedConditionalLogic)) {
        conditionalLogicDependencies[from] ??= false
        const referencedFieldPaths = conditionalLogicResolver.getReferencedFieldPaths(from)
        for (const to of referencedFieldPaths) {
          conditionalLogicDependencies[to] = true
        }
      }
    }
    if (queue.some((path) => path === '$resolve' || conditionalLogicDependencies[path])) {
      conditionalLogic.value = conditionalLogicResolver.setInput(data.value).resolve()
    }
  }
}, 50)

function setData(value: Record<string, any> | null | undefined) {
  const newData: Record<string, any> = {}
  for (const [fieldName, options] of Object.entries(structure.data?.fields ?? {})) {
    if (isDefined(value?.[fieldName])) {
      newData[fieldName] = value![fieldName]
      Object.assign(options, deserializeTranslatableStringCallbacks(options))
    }
  }
  data.value = newData
}

const saveData = lockAndLoad(isSubmitting, async () => {
  const preparedData = prepareFieldData(data.value, structure.data.fields, history.getOriginalState())
  const response = await pruviousDashboardPatch('me', { body: preparedData, inputErrors: errors })

  if (response.success) {
    setData(response.data)
    history.push(data.value).setOriginalState(data.value)

    if (isDefined(data.value.contentLanguage)) {
      contentLanguage.value = data.value.contentLanguage
    }

    const languageChanged =
      isDefined(data.value.dashboardLanguage) && data.value.dashboardLanguage !== dashboardLanguage.value
    const smartClipboardChanged =
      isDefined(preparedData.smartClipboard) && preparedData.smartClipboard !== auth.value.user?.smartClipboard

    if (languageChanged || smartClipboardChanged) {
      const action = await puiDialog({
        content: __(
          'pruvious-dashboard',
          languageChanged
            ? 'The dashboard language has been updated. Please reload the page for the changes to take effect.'
            : 'Some system settings have been updated. Please reload the page for the changes to take effect.',
        ),
        actions: [
          { name: 'later', label: __('pruvious-dashboard', 'Later') },
          { name: 'reload', label: __('pruvious-dashboard', 'Reload'), variant: 'primary' },
        ],
      })

      if (action === 'reload') {
        location.reload()
        return
      }
    }

    Object.assign(auth.value.user ?? {}, response.data)
    puiQueueToast(__('pruvious-dashboard', 'Saved'), { type: 'success' })
  } else if (response.error.statusCode === 422) {
    errors.value = response.error.data as Record<string, string>
    puiQueueToast(__('pruvious-dashboard', 'Found $count $errors', { count: Object.keys(errors.value).length }), {
      type: 'error',
    })
  }
})

async function signOutOtherDevices() {
  const action = await puiDialog({
    content: __(
      'pruvious-dashboard',
      'Are you sure you want to Sign out from all other devices? Your current session will remain active.',
    ),
    actions: [
      {
        name: 'cancel',
        label: __('pruvious-dashboard', 'Cancel'),
      },
      {
        name: 'sign-out',
        label: __('pruvious-dashboard', 'Sign out'),
        variant: 'primary',
      },
    ],
  })

  if (action === 'sign-out') {
    const query = await pruviousDashboardPost('auth/logout/others', {})

    if (query.success) {
      storeAuthToken(query.data.token)
      puiQueueToast(__('pruvious-dashboard', 'Signed out'), { type: 'success' })
    }
  }
}
</script>
