name: ci

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - v4
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - v4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies (and build)
        run: pnpm install

      - name: Publish on pkg.pr.new
        run: pnpm pkg-pr-new publish './packages/*'
